# -*- coding: utf-8 -*-
"""Overwrite chatgptHighlights for Java textbooks 20260717-51 (5th) and -52 (7th)."""
from __future__ import annotations

import json
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

ROOT = Path(r"C:\Users\johso\OneDrive\Desktop\Johsok_BookReading")
sys.path.insert(0, str(ROOT))
from tools.findbook_writer import validate_highlights

TAIPEI = ZoneInfo("Asia/Taipei")
NOW = datetime.now(TAIPEI)
STAMP = NOW.isoformat(timespec="seconds")
UPDATED = "2026-08-18"

# Flag SWT 5th ed: classic classroom Java (JDK PATH, Vector/Hashtable, StringBuffer, AWT/Swing, applet).
HL51 = [
    "安裝 JDK 後要把 bin 加進 PATH，命令列才找得到 javac 與 java。",
    "CLASSPATH 設錯時編譯成功的 .class 執行會變成 NoClassDefFoundError。",
    "原始檔名必須與 public class 完全相同，副檔名只能是 .java。",
    "進入點固定寫 public static void main(String[] args)，少修飾詞就啟動不了。",
    "javac 產出位元碼檔，java 指令載入類別並從 main 開始跑。",
    "套件目錄層級必須對上 package 宣告，否則類別載入器找不到檔。",
    "識別字可含字母、數字、底線與錢號，但第一個字元不能是數字。",
    "class、static、void、new 這類關鍵字禁止當識別字，編譯會立刻失敗。",
    "byte 範圍是負 128 到 127，超出時賦值必須明確強制轉型。",
    "int 除以 int 會捨去小數，五除以二得到二而不是二點五。",
    "long 常數字尾要加 L，否則超過 int 上限的數字編譯不過。",
    "float 常數字尾要加 f，否則 3.14 會被當成 double 塞不進 float。",
    "char 用單引號包一個 16 位元 Unicode 字元，例如 'A' 或中文字。",
    "boolean 只允許 true 與 false，不能拿 0 或 1 當邏輯值。",
    "整數溢位不會丟例外，int 最大值再加一會繞回負數。",
    "前置遞增先改值再取用，後置遞增先取用再改值，條件式裡最容易寫反。",
    "邏輯運算 && 與 || 會短路，左邊已能定案時右邊方法根本不執行。",
    "單一 & 或 | 用在 boolean 時兩邊都會算完，副作用可能被意外觸發。",
    "基本型別相等用雙等號，字串內容相等必須呼叫 equals。",
    "兩個分別 new 出來的相同文字，參考不同，雙等號比較會得到 false。",
    "字串一經建立就不能改內容，replace 只會傳回另一個新物件。",
    "迴圈裡反覆用加號串字會製造大量暫時物件，課堂範例改用 StringBuffer。",
    "StringBuffer 的 append 改的是同一個可變緩衝，最後再 toString 一次即可。",
    "三元運算條件問號真值冒號假值，只能當運算式不能取代整段敘述。",
    "if 後面若省略大括號，只有緊接的那一行屬於該條件。",
    "switch 的 case 在舊語法只能對整數、字元或列舉，忘記 break 會貫穿下去。",
    "for 迴圈三個區段是起始、條件、迭代，條件一開始就假則主體零次。",
    "while 先測條件再跑，可能一次都不進迴圈本體。",
    "do-while 至少執行一次，條件寫在結尾分號前面。",
    "break 立刻離開最內層迴圈或 switch，continue 則跳到下一次迭代。",
    "標籤 break 可一次跳出雙層巢狀迴圈，名稱寫在外層前面。",
    "陣列用 new int[長度] 配置，length 是欄位不是方法。",
    "索引從零起算，讀到等於長度的位置會丟 ArrayIndexOutOfBoundsException。",
    "陣列變數只是參考，兩個變數指向同一塊記憶體時改一邊另一邊也變。",
    "二維陣列本質是陣列的陣列，每一列長度可以不同。",
    "System.arraycopy 可把一段元素拷到另一陣列，手動迴圈容易漏邊界。",
    "方法參數是傳值，基本型別在方法內改掉不會影響呼叫端變數。",
    "傳物件參考時改的是物件欄位，呼叫端看得到欄位變化。",
    "同名方法參數型別或個數不同叫多載，回傳型別不同不足以構成多載。",
    "方法若宣告回傳型別，每條路徑都要 return，否則編譯失敗。",
    "區域變數沒有預設值，使用前必須先賦值。",
    "成員變數未初始化時數字為零、boolean 為 false、參考為 null。",
    "類別是藍圖，new 之後才得到真正佔記憶體的物件。",
    "this 指向目前這個物件，可把參數名稱與欄位名稱區隔開。",
    "static 欄位屬於類別一份，所有實例共用，改了大家一起變。",
    "static 方法不能直接碰尚未指定物件的實例欄位，必須經由參數傳入。",
    "建構子名稱與類別相同且沒有回傳型別，new 時自動呼叫。",
    "若自己寫了有參數建構子，編譯器就不再提供無參數版本。",
    "this() 必須放在建構子第一行，用來轉呼叫同類別另一個建構子。",
    "private 欄位只能在類別內部碰，外面要靠取值與設定方法。",
    "public 成員任何套件都看得到，protected 還允許子類別存取。",
    "沒寫存取修飾時是套件權限，只有同套件類別能用。",
    "封裝把欄位藏起來，設定方法裡可檢查負數或空字串。",
    "extends 只能繼承一個父類別，Java 課堂語法不允許多重類別繼承。",
    "子類別建構子第一行常呼叫 super(...)，用來初始化父類別欄位。",
    "沒寫 super() 時編譯器會自動插無參數父建構子，父類別若沒有就編譯失敗。",
    "覆寫方法簽章必須對上，包含名稱、參數與相容的回傳型別。",
    "private 方法不能被覆寫，子類別寫同名只是另一個新方法。",
    "Object 是所有類別的根，toString、equals、hashCode 預設行為常需改寫。",
    "父類別變數可指向子類別物件，呼叫時依實際型別決定用哪份覆寫方法。",
    "編譯期只看變數宣告型別，所以父型別沒有的方法不能直接呼叫。",
    "向下轉型前先用 instanceof 檢查，硬轉失敗會丟 ClassCastException。",
    "抽象類別不能 new，專門留給子類別去補抽象方法。",
    "抽象方法沒有方法體，具體子類別必須全部實作否則自己也得保持抽象。",
    "抽象類別仍可擁有一般方法與欄位，用來放共用邏輯。",
    "介面在此版教材以全部抽象方法加上 public static final 常數為主。",
    "類別用 implements 接介面，可同時實作多個介面補足單繼承限制。",
    "介面參考可指向任何實作類別，呼叫時走該類別的實作。",
    "package 宣告必須是檔案第一句有效敘述，對應磁碟目錄結構。",
    "import 只是讓簡名可用，真正載入仍靠套件路徑與 CLASSPATH。",
    "java.lang 自動匯入，String 與 System 不必手動 import。",
    "try 包可能失敗的敘述，catch 依例外型別由窄到寬排列。",
    "finally 無論有沒有例外都會跑，常拿來 close 檔案串流。",
    "checked 例外若不處理就必須在方法簽章寫 throws，否則編譯不過。",
    "RuntimeException 與 Error 屬 unchecked，編譯器不強制捕捉。",
    "throw 丟出一個例外物件，throws 則是方法對呼叫端的宣告。",
    "catch 裡若只印堆疊卻吞掉例外，上層完全不知道失敗原因。",
    "NumberFormatException 常出現在 Integer.parseInt 吃到非數字字串。",
    "NullPointerException 代表對 null 參考呼叫方法或讀欄位。",
    "File 物件只描述路徑，new File 並不會自動在磁碟建立檔案。",
    "FileWriter 預設覆寫整個檔，若要接續寫入需用可附加的建構子。",
    "FileReader 一次讀字元，搭配 BufferedReader 的 readLine 較適合逐行。",
    "讀檔迴圈要以 read 回傳負一當結束，不要假設一定讀到固定長度。",
    "串流用完必須 close，否則檔案鎖在 Windows 上常關不掉。",
    "Integer.parseInt 把十進位文字轉 int，前導空白或逗號都會失敗。",
    "包裝類別如 Integer 可把基本型別放進只能存物件的集合。",
    "Vector 的方法大多同步，課堂用 addElement、elementAt、size 操作清單。",
    "Hashtable 的鍵值都不能是 null，put 進去後用 get 取回。",
    "Enumeration 搭配 Vector 的 elements()，用 hasMoreElements 與 nextElement 走訪。",
    "ArrayList 已出現在此版補充，預設非同步，單執行緒練習較常用。",
    "集合存的是物件參考，基本型別要先包成 Integer 或 Double。",
    "Hashtable 的鍵必須正確實作 equals 與 hashCode，否則 get 不到剛 put 的值。",
    "Vector 允許重複元素，搜尋時 indexOf 找到第一個就停。",
    "繼承 Thread 後覆寫 run，start 才會真的開新執行緒，直接呼叫 run 仍在原執行緒。",
    "實作 Runnable 把工作與執行緒物件分開，同一工作可丟給不同 Thread。",
    "synchronized 鎖的是物件，兩個執行緒搶同一把鎖才會互斥。",
    "wait 必須在 synchronized 區塊內呼叫，否則丟 IllegalMonitorStateException。",
    "notify 只叫醒一個等待者，notifyAll 叫醒該鎖上所有等待執行緒。",
    "執行緒結束後不能再 start，要重跑必須 new 另一個 Thread。",
    "AWT 的 Frame 是頂層視窗，要 setSize 再 setVisible(true) 才看得到。",
    "FlowLayout 由左到右排元件，視窗變窄時自動折行。",
    "BorderLayout 分東西南北中五區，中間元件會吃掉剩餘空間。",
    "GridLayout 把容器切成等大格子，適合計算機按鈕。",
    "Button 要註冊 ActionListener，actionPerformed 裡才寫按下後的邏輯。",
    "事件處理若做太久會卡住 AWT 事件執行緒，畫面會暫時沒反應。",
    "Swing 元件名稱多半加 J，例如 JFrame、JButton、JPanel。",
    "JFrame 的內容應加到 content pane，直接加到 JFrame 本體常排版怪異。",
    "Swing 建議在事件執行緒建立介面，課堂範例仍常見在 main 直接 new JFrame。",
    "Applet 沒有 main，瀏覽器呼叫 init、start、stop、destroy 生命週期。",
    "applet 標籤把 .class 嵌進網頁，本機檔案協定常被瀏覽器安全政策擋住。",
    "paint(Graphics g) 裡畫圖，改狀態後要 repaint 才會重畫。",
    "內部類別可直接使用外部類別的成員，適合把監聽器寫在視窗類別裡。",
    "匿名內部類別常在 addActionListener 參數位置現場實作介面。",
    "靜態內部類別不持有外部實例，可獨立 new，像一般套疊類別。",
    "區域內部類別定義在方法內，外面方法結束後仍可能被監聽器引用。",
    "畫布座標原點在左上，x 向右 y 向下，跟數學座標習慣相反。",
    "Color 用紅綠藍三個 0 到 255 的整數組出顏色。",
    "Font 指定字型名稱、樣式與點數，繪字前先 setFont。",
    "命令列引數從 args[0] 開始，沒傳參數就取用會越界。",
    "System.out.println 會換行，print 則停在同一行繼續。",
    "註解雙斜線到行尾，斜線星號可跨多行，文件註解用斜線雙星。",
    "運算子優先順序乘法高於加減，不確定時加括號最保險。",
    "強制轉型把較寬型別變窄會丟失高位元，double 轉 int 會丟掉小數。",
    "字元與整數可互轉，'0' 的整數值不是零，要得到數字零需減 '0'。",
    "短路與非短路混用時，除以零可能被左邊擋住或被右邊真正執行。",
    "巢狀 if-else 配對就近原則，else 屬於最近那個還沒配對的 if。",
    "多維陣列用 array.length 拿列數，array[i].length 拿該列長度。",
    "方法遞迴必須有終止條件，否則會 StackOverflowError。",
    "equals 覆寫時應同時覆寫 hashCode，否則當 Hashtable 鍵會遺失。",
    "finalize 在此版可能被提到，但不保證何時執行，釋放檔案仍應自己 close。",
    "instanceof 對 null 結果是 false，不會丟例外。",
    "介面常數預設 public static final，實作類別可直接用簡名。",
    "編譯警告與錯誤不同，錯誤必須修，警告仍可能產出 .class。",
    "Windows 大小寫不敏感但 Java 識別字大小寫有別，檔名與類別名仍應對齊。",
    "main 的 args 長度為零時不要假設一定有檔名參數。",
    "Vector 的 capacity 與 size 不同，size 才是目前元素個數。",
    "Hashtable 走訪用 keys() 或 elements() 的 Enumeration，順序不保證。",
    "AWT 與 Swing 混用同一頂層視窗容易出現重疊與更新不同步。",
    "applet 預設沙盒不能任意寫本機檔，課堂示範常改成獨立 Application。",
    "內部類別編譯後檔名會含錢號，例如 Outer$Inner.class。",
    "String 的 intern 與字面常數池有關，教材用來解釋為何有時雙等號碰巧為真。",
    "charAt 索引超出字串長度會丟 StringIndexOutOfBoundsException。",
    "substring 的結束索引不含該位置，容易把切割點算多一格。",
    "BufferedWriter 記得 flush 或 close，否則緩衝區內容可能還沒進檔。",
    "DataInputStream 讀二進位 int 時位元組順序依 Java 規定，與純文字檔不同。",
    "Thread.sleep 會拋受檢的 InterruptedException，必須捕捉或往外丟。",
    "setPriority 只能影響排程傾向，不能拿來當同步機制。",
    "JTextField 取字用 getText，數字還要再 parseInt，空白會失敗。",
    "視窗關閉事件若沒處理，點 X 可能只藏起元件而行程還在。",
    "Graphics 的 drawString 基線在指定 y，中文與英數字高不同時容易裁切。",
    "layout 設成 null 後必須自己 setBounds，否則元件寬高為零看不到。",
    "同一 ActionListener 可掛多顆按鈕，用 getSource 或 setActionCommand 分辨。",
    "課堂練習把商業邏輯寫進 actionPerformed 過長時，應抽成獨立方法。",
    "編譯與執行目錄不一致時，套件類別要用完整套件名啟動。",
    "float 累加誤差明顯，金額計算課堂仍常用 int 存分或改用 BigDecimal 補充。",
    "boolean 運算不可寫成 if(x=true) 那種賦值，條件必須是布林運算式。",
    "switch 漏 default 時未列到的值會安靜跳過，除錯較困難。",
    "陣列可在宣告時用大括號初始化，長度由元素個數決定。",
    "物件陣列預設每個格子是 null，沒 new 元素就呼叫方法會空指標。",
    "靜態初始化區塊在類別第一次載入時跑一次，適合放共用表格。",
    "實例初始化區塊每次 new 都會跑，且早於建構子本體。",
    "覆寫時不可縮小存取權，父類 public 的方法子類不能改成 private。",
    "介面方法在此版教材視為隱含 public abstract，實作時不可漏 public。",
    "catch 多個例外若有繼承關係，子型別必須寫在父型別前面。",
    "printStackTrace 方便除錯，交作業成品應改成對使用者可讀的訊息。",
    "File 的 exists、isFile、isDirectory 要先問清楚，才決定讀檔或列目錄。",
    "RandomAccessFile 可跳到指定檔案指標，適合記錄固定長度資料。",
    "Vector 轉成陣列可用 copyInto，長度必須先準備夠。",
    "Hashtable.containsKey 與 contains 不同，一個查鍵一個查值。",
    "執行緒 join 會等對方結束，main 結束不等子執行緒時行程可能提前離開。",
    "AWT 的 Panel 可再嵌套，複雜畫面用多層容器組合較清晰。",
    "Swing 的 JOptionPane 可快速跳出訊息框，練習輸入對話也常用。",
    "applet 的 getParameter 讀 HTML 參數，缺參數時要給預設值。",
    "匿名類別沒有建構子名稱，若要帶外層資料就用外層 final 區域變數。",
    "此版不以 var、模組系統、record 或 sealed 當主軸，打穩類別與例外即可。",
]

# Flag SWT 7th revised: Java 8–11 classroom (lambda, Stream, Optional, java.time, var, modules, NIO.2).
HL52 = [
    "修訂第七版課堂以 Java 8 到 11 為主，編譯可用 javac --release 控制目標版本。",
    "區域變數型別推斷用 var，只能在有初始化的區域變數，不能當方法參數。",
    "var 推斷失敗常見於初始化成 null 卻沒給目標型別，編譯器無法決定。",
    "模組系統入門會碰到 module-info.java，exports 決定哪些套件給外面。",
    "unnamed module 仍能跑舊式 classpath 程式，轉模組時缺 requires 會連結失敗。",
    "Lambda 寫成參數箭頭主體，右側若是運算式可省略大括號與 return。",
    "Lambda 能對到的目標必須是單一抽象方法的函數式介面。",
    "Predicate 測條件、Function 做轉換、Consumer 只消費、Supplier 只供應。",
    "方法參考用類別名稱雙冒號方法名，可取代只轉呼叫既有方法的 Lambda。",
    "建構子參考寫成 Type::new，常搭配 Stream 的 map 產生新物件。",
    "Lambda 捕捉的區域變數必須實質上是 final，迴圈裡改計數器會編譯失敗。",
    "介面可寫 default 方法，舊實作類別不必立刻改就能獲得新行為。",
    "介面也可宣告 static 方法，呼叫時用介面名稱點方法，不能靠實例多型。",
    "Java 9 起介面能寫 private 方法，用來拆開重複的 default 邏輯。",
    "Stream 管線分中間操作與終端操作，沒接終端操作時中間步驟不會真正跑。",
    "filter 留下符合 Predicate 的元素，map 把每個元素轉成另一種型別。",
    "flatMap 把每個元素展開成子串流再接平，適合處理集合套集合。",
    "collect(Collectors.toList()) 把串流收成 List，不要在 forEach 裡自己 add。",
    "Collectors.groupingBy 依分類鍵分組，value 預設是該組的 List。",
    "Collectors.joining 專收字串，可指定分隔符、前綴與後綴。",
    "reduce 需要單位元素與結合運算，空串流時單位元素就是答案。",
    "findFirst 回 Optional，空串流時不要假設一定有值再 get。",
    "anyMatch 一找到符合就可短路結束，不一定走完整份資料。",
    "sorted 若不給 Comparator 就用自然順序，元素必須實作 Comparable。",
    "distinct 依 equals 去重，自訂類別沒覆寫 equals 時去重幾乎無效。",
    "limit 與 skip 用來做分頁，skip 很大時對有序串流成本仍不低。",
    "parallelStream 會切執行緒，有共享可變累加器時結果不穩定。",
    "Optional.empty 代表沒有值，of 不能傳 null，可能為空時用 ofNullable。",
    "orElse 給備援值，orElseGet 才用 Supplier 延遲計算備援。",
    "orElseThrow 在沒有值時丟例外，比直接 get 更符合語意。",
    "map 與 flatMap 在 Optional 上可持續轉換，避免層層 if null。",
    "ifPresent 只在有值時執行 Consumer，沒有值就安靜略過。",
    "java.time 的 LocalDate 沒有時區，of(年, 月, 日) 建立日期。",
    "LocalDateTime 含當日時刻，格式化用 DateTimeFormatter 而非舊 SimpleDateFormat。",
    "Instant 表示時間軸上的瞬間，跨時區計算應先轉成 Instant 或 ZonedDateTime。",
    "Duration 量時間長短，Period 量年月日差，兩者不可隨意混用。",
    "plusDays 傳回新物件，LocalDate 本身不可變，舊變數不會被改到。",
    "解析使用者輸入日期失敗會丟 DateTimeParseException，要單獨捕捉。",
    "舊的 Date 與 Calendar 可變且月從零起算，第七版改教 java.time 避開這些坑。",
    "字串拼接在迴圈中改用 StringBuilder，它不像 StringBuffer 那樣同步。",
    "StringBuilder 的 reverse、delete、insert 都改同一個緩衝，最後 toString。",
    "字串 join 可用 String.join 或 Collectors.joining，分隔符不會出現在尾端。",
    "isBlank 在 Java 11 可判斷空白字元，isEmpty 只看長度是否為零。",
    "strip 會去掉 Unicode 空白，trim 行為與舊版不完全相同。",
    "repeat 讓同一字串重複 n 次，比手動 StringBuilder 迴圈短。",
    "NIO.2 用 Paths.get 得到 Path，再交給 Files 做讀寫，而不是先 new File。",
    "Files.readAllLines 一次讀成 List，大檔會佔記憶體，可改用 newBufferedReader。",
    "Files.write 預設覆寫，若要附加要加 StandardOpenOption.APPEND。",
    "Files.exists 與 notExists 都可能因權限回傳不明，不能當絕對互斥。",
    "walk 可遞迴走目錄樹，必須在 try-with-resources 關閉 Stream。",
    "copy 與 move 要處理目標已存在，可傳 REPLACE_EXISTING。",
    "讀寫通道失敗時例外多為 IOException，方法簽章常直接 throws。",
    "泛型鑽石運算子 new ArrayList<>() 讓編譯器推斷右側型別參數。",
    "List<String> 不能直接塞 Integer，編譯期就擋住混放。",
    "ArrayList 隨機存取快，中間 insert 要搬移後段元素。",
    "LinkedList 實作 Queue 時用 offer 與 poll，空佇列 poll 回 null。",
    "HashMap 允許一個 null 鍵，get 不到時回 null，與值真的是 null 無法分辨。",
    "computeIfAbsent 只在鍵不存在時計算一次，適合做快取對應表。",
    "merge 可把舊值與新值用函數合併，計數器範例常加一。",
    "forEach 在 Map 上接收鍵與值兩個參數的 BiConsumer。",
    "HashSet 去重依 hashCode 與 equals，可變物件當元素後改欄位會丟失。",
    "List.of 與 Set.of 產生不可變集合，再 add 會丟 UnsupportedOperationException。",
    "Map.of 最多十對鍵值，更多要用 ofEntries。",
    "不可變集合元素不能是 null，跟 HashMap 允許 null 的習慣不同。",
    "try-with-resources 在圓括號宣告 AutoCloseable，離開區塊自動 close。",
    "try 括號裡可宣告多個資源，關閉順序與宣告順序相反。",
    "close 時若再丟例外，會以 suppressed 掛在主要例外上。",
    "手動 finally close 容易漏寫，第七版範例優先改成 try-with-resources。",
    "受檢例外仍要處理，Lambda 主體裡不能直接 throws IOException 給 Stream。",
    "包裝成 UncheckedIOException 是常見權宜，呼叫端仍應記錄原因。",
    "多 catch 可用直條合併相同處理，型別之間不能有繼承關係。",
    "有效最終變數才能進 Lambda，重新賦值就算看起來沒改用途也會被拒。",
    "Comparator.comparing 抽出鍵再比，thenComparing 做第二排序鍵。",
    "reversed 得到反向比較器，nullsFirst 可決定 null 排前或排後。",
    "sort 直接改 List，sorted 在 Stream 上產生新順序而不改來源集合。",
    "Iterator 的 forEachRemaining 可接 Consumer，與增強 for 迴圈並存。",
    "removeIf 依 Predicate 刪除，比邊走訪邊 remove 安全。",
    "replaceAll 對 List 每個元素套 UnaryOperator，字串可統一轉大寫。",
    "Stream 只能消費一次，終端操作後再 filter 會丟 IllegalStateException。",
    "無限串流用 iterate 或 generate，必須搭配 limit 否則終端操作停不了。",
    "IntStream 避免反覆裝箱，sum 與 average 是基本型別串流才有的終端。",
    "mapToObj 把 IntStream 轉回物件串流，才能接 Collectors。",
    "peek 只該除錯用，靠 peek 改外部狀態會讓平行串流很難講。",
    "groupingBy 下游可再 averagingInt，一次收集完成統計。",
    "partitioningBy 依布林條件分成 true 與 false 兩組 Map。",
    "Optional 不該當方法參數或集合元素，空值語意會變模糊。",
    "序列化作業仍可能碰到舊 Date，轉換橋樑是 Date.toInstant。",
    "JFrame 在第七版仍是桌面練習主力，元件加到 getContentPane 或直接 add。",
    "Lambda 可當 ActionListener，因為該介面只剩一個 actionPerformed。",
    "SwingUtilities.invokeLater 把介面建構丟回事件執行緒，避免執行緒違規。",
    "JTable 資料常放在 TableModel，改資料後要 fire 通知畫面重繪。",
    "JFileChooser 回傳 APPROVE_OPTION 才去讀 Path，取消時不要硬轉檔。",
    "事件處理裡呼叫 Files 讀檔時，慢磁碟會卡住介面，可改用背景工作執行緒。",
    "模組化後 javax.swing 要在 module-info 寫 requires java.desktop。",
    "java.base 自動可用，String 與 Collection 不必額外 requires。",
    "split 套件時小心循環依賴，兩個模組互相 requires 會讓編譯卡住。",
    "反射讀未 exports 的套件會被模組邊界擋住，課堂示範常先關掉模組再對照。",
    "var 不能宣告成多個變數同一行，也不可當欄位型別。",
    "匿名類別與鑽石運算子並用時，有時仍要在 new 後面寫出型別參數。",
    "泛型抹除後執行期看不到 Type 參數，instanceof List<String> 不合法。",
    "通配 ? extends 適合生產者，? super 適合消費者，PECS 口訣課堂會提到。",
    "捕獲通配後不能隨意 add，除了 null，否則破壞型別安全。",
    "方法參考與多載同時存在時，編譯器可能無法選定，需寫回 Lambda 標型別。",
    "例外在 Stream.map 裡若是受檢，常抽成包一層的輔助方法。",
    "Files.readString 與 writeString 是 Java 11 的小檔便捷 API。",
    "InputStream 的 transferTo 可把位元組轉進 OutputStream，減少自寫緩衝迴圈。",
    "Charset 明確指定 UTF-8，避免 Windows 預設編碼把中文讀亂。",
    "Path 的 resolve 接相對路徑，resolveSibling 則換同層檔名。",
    "normalize 清掉 . 與 ..，toRealPath 才會碰到實際檔案系統並跟隨連結。",
    "目錄串流 DirectoryStream 也要關掉，否則檔案控制代碼會漏。",
    "WatchService 可監看目錄變更，教材僅入門，輪詢仍較常見於作業。",
    "HttpClient 在 Java 11 標準庫，send 同步、sendAsync 回 CompletableFuture。",
    "BodyHandlers.ofString 把回應收成字串，狀態碼不是 2xx 時仍可能有本體。",
    "CompletableFuture.thenApply 做轉換，thenCompose 避免 Optional 式的未來套未來。",
    "join 在 future 上會把例外包成 CompletionException，get 則丟 ExecutionException。",
    "Executor 自己建立時記得 shutdown，否則精靈執行緒會讓程式關不掉。",
    "synchronized 清單還在，但教材改推 ConcurrentHashMap 做高併發對照。",
    "CopyOnWriteArrayList 適合讀多寫少，每次寫都複製整份陣列。",
    "Thread 仍可 new，但作業較常把工作丟進 Executors.newFixedThreadPool。",
    "Callable 能回傳值並丟例外，Future.get 會阻塞到算完。",
    "中斷執行緒應檢查 interrupted 旗標，不能只靠 stop，那方法已廢棄。",
    "try-with-resources 也能管理自訂資源，只要實作 close。",
    "AutoCloseable 的 close 不該丟過重例外，以免掩蓋 try 主體的真正錯誤。",
    "記錄型別與 sealed 不是此版主軸，課堂重點停在 Lambda 與模組入門。",
    "switch 在 Java 11 仍是傳統 case 加 break，箭頭式 switch 尚未進教材核心。",
    "文字區塊尚未成為 Java 11 課堂標配，長字串仍用連接或文字檔。",
    "var 搭配匿名類別時推斷成該匿名型別，後面不能當一般介面再賦值。",
    "泛型方法呼叫可寫 ClassName.<String>method()，多數情況可省略。",
    "型別註解與 @Override 仍建議寫上，覆寫失敗時編譯器會警告。",
    "equals 與 hashCode 在 HashMap 鍵上同樣關鍵，可用 Objects.equals 避開空值。",
    "Objects.requireNonNull 在進入方法時就擋 null，錯誤訊息可自訂。",
    "List.copyOf 做防禦性拷貝，外層再改來源清單也不會影響副本。",
    "toArray(new String[0]) 是較安全的轉陣列寫法，長度零讓 JVM 配置正確大小。",
    "iterator 與 forEach 同時改同一 ArrayList 仍可能 ConcurrentModificationException。",
    "subList 只是原清單視圖，清掉 subList 等於清掉原清單對應區段。",
    "TreeMap 依鍵排序，鍵必須可比較或建立時傳入 Comparator。",
    "NavigableMap 的 lowerKey 與 ceilingKey 適合做範圍查詢。",
    "Properties 讀 .properties 時注意編碼，Java 9 起可用 Reader 指定 UTF-8。",
    "ResourceBundle 依 Locale 換訊息檔，缺鍵會往父 Locale 找。",
    "Logger 用 java.util.logging 入門，級別設錯會讓 INFO 訊息全部消失。",
    "assert 預設關閉，教學示範要加 -ea 才看得到斷言失敗。",
    "javac -d 指定輸出目錄對應套件樹，再 java -cp 該目錄跑主類別。",
    "單一檔案原始碼啟動是 Java 11 的 java Hello.java，適合小練習不必先 javac。",
    "shebang 檔可把 java 當腳本跑，Windows 課堂較少用，Linux 示範較常見。",
    "垃圾收集仍自動，教材重點是不要抓住不用的大集合參考。",
    "字串與常數池關係仍在，但比較內容一律 equals，不要靠雙等號碰運氣。",
    "BigDecimal 用字串建構避免 0.1 的 double 誤差，金額加減指定 scale 與捨入。",
    "Math 的 floorMod 對負數取餘較符合週期，% 在負數時符號跟被除數。",
    "switch 字串比對從 Java 7 就有，記得 null 會丟例外。",
    "列舉可實作介面並寫方法，比一堆 public static final int 安全。",
    "註解可標在型別參數，課堂只需認識 @Override 與 @FunctionalInterface。",
    "@FunctionalInterface 可防止後來有人再加第二個抽象方法破壞 Lambda。",
    "串流來源若是陣列用 Arrays.stream，基本型別陣列要用 IntStream 特化版。",
    "Collection.remove 依 equals 刪第一個，removeIf 才能一次刪所有符合者。",
    "Map.putIfAbsent 舊值存在就不覆寫，回傳的是舊值而非布林。",
    "compute 每次都重算，就算鍵已存在，和 computeIfAbsent 不同。",
    "replace(key, old, new) 採原子條件更新，值不符就失敗。",
    "第七版把 Hashtable 與 Vector 當歷史對照，新練習改寫 ArrayList 與 HashMap。",
    "NIO.2 的 Files.deleteIfExists 檔案不在時回 false，不必先 exists 再開刪。",
    "建立目錄用 createDirectories 可一次建中間層，createDirectory 缺父層會失敗。",
    "讀取屬性 size 與 lastModifiedTime 經 Files，不要混用舊 File.length 兩套 API。",
    "Path 相等比較 equals 看文字形式，isSameFile 才問檔案系統是否同一檔。",
    "模組路徑用 --module-path，跟舊 -cp 同時出現時要搞清楚類別從哪邊來。",
    "自動模組把 jar 檔名當模組名，檔名不合規則時連結錯誤很難讀。",
    "服務載入 ServiceLoader 搭配 provides 與 uses，教材只要求看懂宣告。",
    "JPanel 用 BorderLayout 放中心表單、南邊按鈕列，是作業常見排法。",
    "KeyStroke 與 InputMap 可綁快捷鍵，焦點不在按鈕時也能觸發。",
    "DocumentFilter 可在 JTextField 輸入時擋非法字元，比事後 parse 失敗友善。",
    "Swing 例外若在事件執行緒未捕捉，畫面可能停住，可設預設未捕捉處理器。",
    "把耗時 Stream 計算移出 actionPerformed，算完再用 invokeLater 更新標籤。",
    "測試日期邏輯時注入 Clock，才能假裝今天是固定的 LocalDate。",
    "withYear 這類方法同樣回傳新日期，把回傳值丟掉就等於沒改。",
    "時區名稱用 ZoneId.of(\"Asia/Taipei\")，縮寫時區在歷史規則上不可靠。",
    "Period.between 不含結束日，算天數差常改用 ChronoUnit.DAYS。",
    "Formatter 與 String.format 的 %n 代表平台換行，作業交 Linux 助教時較穩。",
]


# Keep exactly 150; retain edition-specific closers that sat past the cut.
HL51 = HL51[:149] + [HL51[174]]
HL52 = HL52[:148] + [HL52[157], HL52[174]]


def numbered(bodies: list[str]) -> list[str]:
    if len(bodies) != 150:
        raise SystemExit(f"expected 150 bodies, got {len(bodies)}")
    return [f"{i:03d}、{body}" for i, body in enumerate(bodies, 1)]


def apply(path: Path, title: str, author: str, bodies: list[str]) -> None:
    highlights = numbered(bodies)
    highlights = validate_highlights(path.stem, highlights, title, author)
    book = json.loads(path.read_text(encoding="utf-8-sig"))
    book["chatgptHighlights"] = highlights
    book["chatgptStatus"] = "complete"
    book["highlightsSource"] = "grok"
    book["highlightsCapturedAt"] = STAMP
    book["updatedAt"] = UPDATED
    path.write_text(
        json.dumps(book, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8-sig",
    )
    saved = json.loads(path.read_text(encoding="utf-8-sig"))
    validate_highlights(
        saved["id"],
        saved["chatgptHighlights"],
        str(saved.get("title", "")),
        str(saved.get("author", "")),
    )
    print(f"PASS {path.name} count={len(saved['chatgptHighlights'])}")
    print(f"  {saved['chatgptHighlights'][0]}")
    print(f"  {saved['chatgptHighlights'][1]}")


def main() -> None:
    p51 = ROOT / "Books/06_computer_info/06_computer_info-20260717-51.json"
    p52 = ROOT / "Books/06_computer_info/06_computer_info-20260717-52.json"
    apply(p51, "最新 Java 程式語言(第5版)", "施威銘研究室", HL51)
    apply(p52, "最新 Java 程式語言 修訂第七版", "施威銘研究室", HL52)


if __name__ == "__main__":
    main()
