# -*- coding: utf-8 -*-
"""Overwrite chatgptHighlights for 06_computer_info-20260716-51/52/53."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(r"C:\Users\johso\OneDrive\Desktop\Johsok_BookReading")
STAMP = "2026-08-18T09:10:00+08:00"
UPDATED = "2026-08-18"
BANNED = ("本書", "作者指出", "本章", "這一章", "｜", "《")
PIPE = "｜"
COLON_TAIL = re.compile(r"[：:]")

HL51 = [
    "Graylog Server 負責接收、處理與查詢，Data Node 上的 OpenSearch 存訊息索引，MongoDB 存組態、使用者與 Pipeline 規則，三者缺一會讓節點看起來活著卻無法登入或無法搜尋。",
    "安裝時把 MongoDB 綁在 replica set，即使單機也先初始化 replica set，否則 Graylog 升級或加入第二個 Server 時會卡在無法寫入叢集組態。",
    "Data Node 的 heap 與 OpenSearch 的 indices.memory.index_buffer_size 要分開估，heap 吃光會讓索引 stall，buffer 太小則大批 ingest 時 flush 過於頻繁。",
    "message_journal 預設落在 Graylog 節點本機磁碟，磁碟滿時會啟用背壓並停止從 journal 讀出，表面症狀是 Input 還在聽但 Search 看不到新訊息。",
    "processbuffer_processors 與 outputbuffer_processors 要依 CPU 核數調，處理慢而輸出快會讓 process buffer 堆積，反向則會讓 output buffer 撐爆 journal。",
    "Syslog UDP Input 不重傳，防火牆 NAT 逾時或封包大於 MTU 會靜默丟事件；關鍵來源改 Syslog TCP 或 GELF TCP 才能用連線狀態判斷中斷。",
    "Syslog TCP 仍可能把多行堆成一則或一切成兩則，需在 Input 設 max message size 並在設備端確認 octet-counting 或 newline framing。",
    "Beats Input 收 Filebeat 時核對 beats 輸出的 Graylog 位址、port 與 TLS，常見失敗是 Filebeat 以為送出成功但 Graylog 因憑證 CN 不符拒收。",
    "GELF UDP 把壓縮 JSON 塞進單一 datagram，超過約 8192 bytes 會被切塊，中間 chunk 遺失整則訊息作廢，大型 exception stack 應改 GELF TCP 或 HTTP JSON。",
    "HTTP JSON Input 適合應用程式直接 POST，務必限制允許的來源 IP 並開 API token 或 TLS client auth，否則公開 endpoint 會變成任意灌垃圾日誌的入口。",
    "Forwarder 把邊緣站點的日誌先在本地緩衝再送到中央 Graylog，WAN 中斷時訊息進 Forwarder spool 而不是直接丟，恢復後要盯 backlog 以免突然灌爆中央 journal。",
    "同一個 Input 不要混收不同廠牌的 Syslog，timestamp 與 hostname 解析規則互相踩踏後，後續 Stream 條件會全部對不到欄位。",
    "Input 的 bind address 若只聽 127.0.0.1，遠端 Beats 連得上防火牆卻永遠進不了 Graylog，要用網卡實際 IP 或 0.0.0.0 並以安全群組收斂來源。",
    "Global Input 會在每個 Graylog Server 啟動同一組聽取埠，負載平衡後訊息可能落到不同節點的 journal，查未索引訊息時要逐台看 journal 使用率。",
    "Extractor 掛在單一 Input，適合把固定格式的 Cisco ASA 或 nginx combined log 拆欄位；來源一多或欄位要跨 Input 共用，應改 Pipeline。",
    "Extractor 的 grok 失敗時預設常留下原始 message，看起來「有進系統」但其實沒有 src_ip，告警條件 source_ip 永遠不會觸發。",
    "正規表示式 Extractor 對多行 stacktrace 很容易 catastrophic backtracking，應限制 message 長度或先用 split 取出第一行再 parse。",
    "JSON Extractor 只拆一層時，nested user.roles 仍是字串，後續 lookup 或 aggregation 會把整個陣列當單一 bucket。",
    "Copy Input Extractor 可把原始 message 備份到 raw_message，Pipeline 改壞後仍能用 raw 重跑 grok，調查時才對得回設備原句。",
    "Pipeline 的 Stage 編號決定執行順序，Stage 0 做 grok 與型別轉換，Stage 1 才做 lookup 與 Stream routing，否則 lookup 會拿到還是字串的 timestamp。",
    "rule 裡用 grok 失敗要 set_field(\"parse_fail\", true) 並 route 到失敗 Stream，不要 drop，否則解析錯誤會被當成「設備沒送」。",
    "from_input(\"Beats\") 這類條件寫錯 Input 名稱時規則靜默不匹配，Pipeline 模擬器要用真實訊息測，不要只看規則語法通過。",
    "lookup 函式要處理 key 不存在，回傳空值時不要覆蓋已有 threat_score，否則正常流量會被舊規則洗成未知。",
    "set_field 把字串 \"443\" 寫進 dest_port 卻沒 to_long，Quick Values 與數值區間告警會把 443 和 80 當字串排序。",
    "Pipeline 的 clone_message 可把一則 Windows Event 拆成登入成功與失敗兩條路徑，但要改 message_id 以免 OpenSearch 文件 _id 碰撞。",
    "正規化欄位名稱用 src_ip、dst_ip、user_name、event_id，不要每個廠牌各一套 sourceaddress，否則跨設備關聯查詢寫不出來。",
    "Stream 規則用欄位精確比對比全文搜尋快，且只有進對的 Stream 才會進對的 Index Set，保存天數才能分等級。",
    "Default Stream 不要當長期存放處，未匹配規則的訊息全堆在這會把熱索引撑爆，應設 catch-all Stream 並給較短 retention。",
    "Remove from Default Stream 勾了之後，規則漏寫會讓訊息消失在所有儀表板，上線前用計數 Widget 對帳 Input throughput。",
    "Index Set 的 rotation 用 Index Time 或 Message Count，高 EPS 來源用訊息數輪替可避免單一 index 過大導致查詢 heap 爆。",
    "retention 設 30 天刪 index，不等於磁碟立刻回來，OpenSearch 還要等 merge 與 replica，容量規劃要算 peak 而非平均值。",
    "熱溫冷層把新 index 放熱節點、舊 index 搬溫節點，查 90 天前事件變慢是預期，調查 playbook 要寫清楚冷資料 SLA。",
    "replicas 在單節點 OpenSearch 設 1 只會黃燈且浪費磁碟，單節點 replica 應為 0，叢集至少三節點才開 replica。",
    "custom mapping 把 src_ip 設成 ip 型別，世界地圖與 CIDR 查詢才有效；當成 text 會分詞，10.0.0.1 對不到 10.0.0.0/8。",
    "欄位爆炸（mapping explosion）來自動態欄位過多，Windows Event 的隨機 XML 標籤要在 Pipeline 白名單，否則 Data Node 會拒絕新 mapping。",
    "Search 的相對時間 last 15 minutes 用瀏覽器時區，Event Definition 用伺服器時區，兩者不一致會讓值班以為告警延遲。",
    "Graylog 與主機 chrony/NTP 不同步時，message timestamp 與 ingest timestamp 差數分鐘，關聯「五分鐘內失敗十次」會算錯窗口。",
    "設備送 UTC、Graylog 顯示 Asia/Taipei，解析時要用 parse_date 指定時區，不要靠瀏覽器自動轉，否則夏令時間地區會偏一小時。",
    "timestamp 解析失敗會退回接收時間，看起來事件「剛好發生在搜尋當下」，調查時要對 raw_message 裡的原始時間字串。",
    "儀表板 Widget 的 Search Filter 要綁 Stream 與 Index Set，全庫搜尋會把測試 Input 的假攻擊畫進正式 SOC 圖表。",
    "Quick Values 適合看 top user_name 或 event_id，但高基數欄位如 session_id 會拖垮聚合，這類欄位不要放統計 Widget。",
    "世界地圖 Widget 需要有 geo_ip 或座標欄位，Lookup Table 接 MaxMind GeoLite2 後寫 geo_country，空值點會全堆在 Null Island。",
    "聚合 Widget 用 count() group by src_ip 做暴力破解熱點，同時加 cardinality(user_name) 才能分辨掃帳號與單一使用者鎖死。",
    "Message Table Widget 要固定顯示 timestamp、source、src_ip、user_name、message，值班點進去才能直接複製調查用的欄位。",
    "儀表板時間範圍不要預設 all messages，開頁會掃完全部熱索引；SOC 牆用 last 1 hour，歷史調查另開 saved search。",
    "Saved Search 把常用查詢存起來，權限要跟 Stream 綁，否則 Guest 角色能靠分享連結看到 AD 密碼噴灑相關日誌。",
    "Event Definition 的 Filter 用 Stream 縮小範圍，Aggregation 設 count()>10 within 5 minutes group by src_ip，才是暴力破解而不是單次登入失敗。",
    "條件用 event_id:4625 且 logon_type:3 過濾網路登入失敗，把 4625 的解鎖螢幕失敗算進去會讓門禁告警爆炸。",
    "Grace period 在同一 group by 鍵觸發後抑制重複通知，寬限太短 Slack 會洗版，太長會把第二次真實攻擊當同一事件吞掉。",
    "Event Deduplication 依欄位雜湊，務必包含 src_ip 與 user_name，只雜湊 rule_id 會讓不同攻擊者共用同一則事件。",
    "Notification 的 Email 要走內部 SMTP 並設 STARTTLS，標題放嚴重度與 Stream 名稱，內文帶 permalink 連回 Graylog 搜尋。",
    "Slack Notification 用 webhook URL 存在 Graylog 機密欄位，頻道分流 critical 與 info，否則測試規則會把正式 on-call 吵醒。",
    "HTTP Notification 打 SOAR 或 ticket API 時要重試與 timeout，對方 500 不能讓 Graylog 事件處理執行緒卡住。",
    "Notification 失敗要另設系統告警看 notification_queue，否則 Event 已觸發但值班群完全沒收到。",
    "Event Definition 先用 Test 與歷史 replay，用昨天的真實 4625 流量回測門檻，不要只靠手動送一筆假訊息。",
    "Sidecar 在 Windows 裝成服務，透過 sidecar.yml 指到 Graylog API，tags 用來下發 winlogbeat 或 filebeat 組態。",
    "Winlogbeat 收 Security、System、PowerShell Operational，event_id 4688 與 4104 對程序建立與腳本區塊特別有用。",
    "Filebeat 收 IIS 或應用程式 log 時要設 prospector 的 close_inactive 與 ignore_older，否則輪替後仍鎖舊檔導致 handle 洩漏。",
    "Sidecar 組態更新後 Collector 沒重載，Graylog UI 顯示 applied 但主機仍用舊 paths，要看 sidecar 日誌的 configuration checksum。",
    "Windows Event 的 Message 是渲染後字串，真正穩定比對應抓 EventData 的 TargetUserName，不要用中文描述當 Stream 條件。",
    "Lookup Table 用 CSV 或 HTTP Data Adapter 載入 IOC，cache 的 TTL 太長會讓已下架的惡意 IP 繼續命中，太短會打爆情資 API。",
    "Data Adapter 失敗時 Lookup 回 fallback，要監控 adapter error 計數，否則情資源掛掉後所有流量被標成 clean。",
    "威脅摘要欄位 threat_family、threat_score 寫進訊息後，儀表板才能依分數上色，只做 lookup 不寫回欄位則 Widget 聚合不到。",
    "同一 IP 在防火牆與 Proxy 日誌出現，要用 lookup 把內部 NAT 對照表轉成真實 user，否則威脅命中停在防火牆位址。",
    "角色權限拆 Reader、Analyst、Admin，Reader 只能查指定 Stream，Analyst 可建 Saved Search 但不能改 Pipeline。",
    "Team 把 SOC 與網管分開，網管 Team 看網路設備 Stream，AD 日誌不要給機房廠商帳號。",
    "Sharing 儀表板時選 Team 而非 Everyone，公開連結在反向代理後仍可能被未授權者用舊 token 打開。",
    "API Token 綁使用者且可設到期，自動化拉取搜尋結果用專用服務帳號，人員離職撤角色時 token 一併失效。",
    "Admin 日常作業不要共用 admin 帳號，審計要能對到誰改了 Extractor 或關掉 Input。",
    "TLS 終止可在反向代理，但 Beats 到 Graylog 的 Input TLS 仍要開，避免機房內橫向竊聽日誌裡的 cookie 與授權標頭。",
    "憑證用內部 CA 簽給 graylog.example.local，Filebeat ssl.certificate_authorities 要放同一 CA，自簽又不停更換會讓全公司 Beats 同時斷線。",
    "憑證到期監控要看 notAfter，Graylog 自己的 Input 失敗計數上升常是第一個訊號，不要等到瀏覽器打不開 Web UI。",
    "HTTP Strict 與 HSTS 只保護 Web UI，Syslog TLS 要用獨立 Input 憑證，兩套到期日分開輪替以免一次維護窗改爆。",
    "時區設定在 Graylog Server 用 TZ=Asia/Taipei，容器若沒傳環境變數，journal 與 UI 會一個 UTC 一個本地。",
    "Windows 主機時區錯誤會讓 Winlogbeat 的 @timestamp 偏掉，Graylog 再怎麼 NTP 正確也關聯不到防火牆同一秒的 drop。",
    "容量用 EPS 估：尖峰 EPS × 平均訊息 2KB × 保存天數 × 1.3 索引膨脹，還要加 replica 與 journal 預留。",
    "journal 使用率超過 75% 就要擴磁碟或降 Input，等到 100% 才告警時，背壓已經開始丟或堵住上游。",
    "背壓發生時優先查哪條 Pipeline grok 過重、哪張 Lookup 同步鎖，而不是先加機器，CPU 可能被單一規則吃滿。",
    "output_batch_size 太大在磁碟慢的 Data Node 會拉長 flush 延遲，搜尋「剛剛發生」的事件會有數十秒可見性落差。",
    "防火牆日誌用 Syslog 收 src、dst、action、rule_id，Stream 條件 action:deny 才能做未授權連線趨勢。",
    "WAF 日誌要保留 rule_id、anomaly_score、request_path，聚合 path 才能看出掃目錄與真實攻擊差在重複度。",
    "AD 的 4624/4625/4672 要進獨立 Index Set 保存較久，權限提升調查常要回看數週前誰被加進 Domain Admins。",
    "Proxy 的 CONNECT 與 HTTP method 欄位可拼出資料外洩，大 POST 到罕見網域要跟 DLP 或 CASB 事件對時間。",
    "雲端 Trail 類事件用 HTTP JSON 收 userIdentity、eventName、sourceIPAddress，ConsoleLogin 失敗要跟 IAM 金鑰濫用分開規則。",
    "AWS CloudTrail 的 AssumeRole 連續出現在不常見 sourceIPAddress，應 lookup 是否為已知 CI 出口，而不是直接當入侵。",
    "暴力破解規則除了失敗次數，要看成功 4624 是否緊接在大量 4625 之後，只告失敗會漏掉已經進去的帳號。",
    "不可能旅行用同一 user_name 兩次成功登入的 geo_country 與時間差，短於合理航程且來源不是 VPN 出口才告警。",
    "權限提升盯 4728、4732、4672，把加入 Domain Admins 或賦予 SeDebugPrivilege 當獨立 Event Definition。",
    "資料外洩模式看 Proxy bytes_out 異常、DNS TXT 長查詢、以及防火牆對非 443 的大量出站，三個來源時間對齊才升級事件。",
    "MITRE 對映把規則標 T1110（密碼噴灑）、T1078（有效帳號）、T1048（外洩），儀表板用 tactic 聚合給管理層看覆蓋，不是拿來當分數遊戲。",
    "Playbook 每則告警要寫：查哪些欄位、何時升級、何時關閉、誤報白名單怎麼進 Lookup Table。",
    "值班 runbook 規定 15 分鐘內認領 Slack 事件，超時升級電話，儀表板紅燈不等於有人正在處理。",
    "視覺化把攻擊畫得很漂亮，若沒有對應關閉條件與事後回顧，SOC 只是在看動畫。",
    "升級路徑先備 MongoDB dump 與 OpenSearch snapshot，再升 Graylog 小版號，Data Node 與 Server 版本差太多會協定不相容。",
    "備份 Mongo 要用 mongodump 含 config、streams、users 集合，只快照磁碟可能備到不完整 journal。",
    "索引備份用 OpenSearch snapshot repository 指到物件儲存，還原測試要在隔離叢集跑一次搜尋，確認 mapping 還在。",
    "故障排除訊息未進索引：先看 Input 計數是否增加，再看 journal uncommitted，再看 OpenSearch cluster health 是否 yellow/red。",
    "cluster red 常是單一 index 的 primary 不見，不要急著刪整個 Index Set，先看哪顆分片未指派。",
    "Pipeline 規則語法上線後 CPU 100%，用 metrics 的 rule.execution.time 找出 grok，改寫或下線該 Stage。",
    "訊息進了 Search 但欄位是空的，對比 Extractor 模擬器與 Pipeline 模擬器，確認不是 Stream 把未解析訊息路由走。",
    "Debug 用 tcpdump 或 Wireshark 看 514/12201 是否有進站，Graylog 計數為零時問題在網路或上游，不在 OpenSearch。",
    "Elasticsearch 相容查詢在 Graylog 5 之後語意有差異，舊 dashboard 的 query_string 大寫 AND 要改成 Graylog 搜尋語法。",
    "Content Pack 匯出 Stream、Pipeline、Dashboard 一併版本化進 git，正式場用匯入而不是在 UI 手改，避免雙人同時覆蓋規則。",
    "測試場與正式場 Index 前綴分開，Content Pack 裡寫死的 Stream id 匯入後要重對通知頻道。",
    "Grok pattern 自訂存成共用 pattern 庫，Windows 與 Linux 的 timestamp 格式不要各寫一份難以維護的複本。",
    "lookup 用 CIDR 表標 RFC1918，告警條件排除內部掃描器 IP，否則每晚弱點掃描會把暴力破解規則打爆。",
    "內部掃描器白名單要有到期日，專案結束後 IP 仍留在 CSV 會變成永久盲區。",
    "多租戶用 Stream 與 Index Set 隔離客戶資料，搜尋權限不能只靠儀表板隱藏 Widget。",
    "個資欄位在 Pipeline 做 hash 或 mask，調查需要明文時走審批後的 decrypt 流程，不要把信用卡號原樣索引。",
    "GDPR 或個資法刪除請求要能依 user_name 找到所有 Index，retention 太長又沒有刪除 API 會讓合規卡住。",
    "EPS 突增常見於除錯 log level 被開成 DEBUG，要對 source 做速率 Widget，單一主機暴量就關 Input 或通知該系統負責人。",
    "Docker 部署要把 journal 與 OpenSearch data 放 volume，容器重建後若 journal 消失會丟尚未索引的訊息。",
    "JVM 參數在 Data Node 不要用超大 heap 超過實體 RAM 一半，其餘留給作業系統 page cache 加速搜尋。",
    "查詢用 named field 而不是 _exists_ 掃全部，全文字搜尋 message:password 在熱索引會拖慢 ingest。",
    "Decorators 把欄位加到搜尋結果顯示，不寫回索引，適合臨時翻譯 event_id，不適合當告警條件來源。",
    "Pipeline 的 metric 計數器可自訂，規則命中數掉到零可能是上游改了欄位名稱而不是攻擊消失。",
    "Forwarder 的 output 批次與壓縮要開，跨海專線才撐得住，未壓縮 JSON 會先打滿頻寬再打滿 journal。",
    "Beats 的 loadbalance 對多個 Graylog 時，Session 親和不必強求，但 TLS 憑證 SAN 要包含所有節點名稱。",
    "HTTP JSON 要驗證 Content-Type 與 body 大小上限，應用程式一次 POST 整份 dump 會讓單則訊息超過 OpenSearch document 限制。",
    "Syslog 的 facility 與 severity 可做 Stream，debug 級別預設 drop 或短 retention，避免開發機污染 SOC 熱索引。",
    "nginx 的 $request_time 與 upstream_status 進 Graylog 後可做應用延遲百分位，這是維運用途，與資安 Stream 分開 Index Set。",
    "資安與維運儀表板分開，CPU 與 5xx 圖不要跟暴力破解放同一牆，值班注意力會被維運噪音帶走。",
    "告警嚴重度 Info/Warn/Critical 要對應通知管道，Info 只寫事件索引不叫人，Critical 才進 on-call。",
    "關閉告警要填原因：誤報、已遏制、轉工單，Graylog 事件狀態若從不更新，週報會以為全是未處理。",
    "定期回顧誤報率，門檻 count()>10 若全是同一掃描器，應改白名單而不是把門檻調到 10000 假裝平靜。",
    "新設備上線 checklist：NTP、時區、Syslog 格式樣本、欄位對照、Stream、retention、告警回測、權限 Team。",
    "下線設備要關 Input 或 Stream 規則，否則過期憑證主機重開機又開始送，索引會出現幽靈 hostname。",
    "OpenSearch 的 max_result_window 不夠時匯出調查結果會失敗，大量取證改用 Search API 的 scroll 或 Graylog 匯出工作。",
    "匯出 CSV 含個資時走審批，API Token 權限不要給無限 export。",
    "使用者登入 Graylog 失敗本身要進稽核，暴力破解監控平台帳號與暴力破解 AD 是兩套規則。",
    "SSO 接 SAML 或 LDAP 後，本地 admin 應留破窗帳號並放實體保險箱，IdP 掛掉不能連平台。",
    "LDAP 群組對角色對應錯誤會讓實習生拿到 Admin，變更群組後要在 Graylog 重登才刷新，測試時不要用快取中的舊角色。",
    "Index 輪替當下搜尋可能短暫缺最新分片，告警窗口不要卡在輪替整點，或接受數十秒延遲。",
    "熱節點磁碟 watermarks 觸發後 OpenSearch 會禁寫，Graylog 表現為 output 失敗與 journal 上升，先騰磁碟再重啟。",
    "shard 數量過多使叢集狀態變肥，小 Index Set 用較長 rotation 減少 shard，不要每天輪替又設 5 主分片給低流量來源。",
    "低流量但高價值的 AD 日誌寧願少分片、長保留，高流量防火牆 deny 可短保留、多分片。",
    "GELF 的 level 與 facility 欄位要 mapping 成數值，才能做 severity<=3 的過濾。",
    "HTTP 輸入的 CORS 不必為日誌開放，那是瀏覽器議題；伺服器對伺服器 POST 應靠網段與憑證。",
    "Pipeline 模擬器貼上真實 Windows XML 時注意換行，UI 把 \\n 吃掉會讓 grok 在正式場才失敗。",
    "規則註解寫「為何存在」與 ticket 編號，三個月後沒人敢刪看起來沒用的 lookup。",
    "Content Pack 不要包 API Token 與 SMTP 密碼，用環境或系統設定注入。",
    "監控 Graylog 自己的 metrics：journal.utilization、processbuffer.usage、org.graylog2.throughput.input。",
    "把這些內部 metrics 再送回一個獨立 Input，避免監控平台的監控與業務日誌搶同一個過載的 Data Node。",
    "升級前看 breaking changes：Pipeline 函式改名、Search 語法、Sidecar 組態 schema，先在測試場跑同樣 EPS。",
    "滾動升級 Server 時 Load Balancer 要摘除節點，否則半升級叢集會讓 Forwarder 打到協定不一致的節點。",
    "MongoDB 磁碟延遲高會讓 UI 改 Stream 卡住，看起來像 Graylog 當機，iostat 要一起看。",
    "OpenSearch 查詢 circuit breaker 觸發時大儀表板全空白，把 Widget 時間範圍縮小或拿掉高基數 aggregation。",
    "世界地圖用 GeoIP 資料庫版本要記錄，舊庫把雲端網段標錯國家會製造假的不可能旅行。",
    "威脅情資 CSV 的欄位分隔與 UTF-8 BOM 常讓第一個 key 對不到，上傳後用 lookup 測試已知 IOC。",
    "容量預留 30% 給調查期大量搜尋，尖峰攻擊當下 SOC 查詢與 ingest 互搶 heap 會兩敗俱傷。",
]

HL52 = [
    "傳統搜尋把問題編成狀態圖，BFS 保證最短步數但記憶體吃掉整層節點，DFS 省記憶體卻可能走進無限深的壞枝。",
    "啟發式搜尋的 A* 要同時滿足 admissible 與 consistent，h(n) 高估真實成本時路徑可以很快但不保證最優。",
    "八數碼這類教材題用曼哈頓距離當 h(n)，比漢明距離（錯位個數）更能引導搜尋，但仍是簡化世界不是通用智慧。",
    "貪婪最佳優先只看 h(n) 不看 g(n)，會在局部看起來近、實際繞遠的地形卡住。",
    "專家系統把知識寫成 if-then，正向鏈從事實推結論，反向鏈從假設找需要的證據，維護成本在規則互相衝突時爆炸。",
    "知識庫與推理機分離的好處是可換規則，壞處是解釋功能若只印觸發過的規則編號，使用者仍看不懂為何拒絕貸款。",
    "監督式學習要有標籤 y，損失函數把預測 ŷ 拉向 y；沒有標籤時硬套準確率這個指標沒有定義。",
    "非監督的 K-means 要事先給 K，SSE 隨 K 下降不能當唯一選模依據，輪廓係數或業務可解釋的群才有意義。",
    "階層式分群的樹狀圖可事後切 K，資料量一大距離矩陣吃記憶體，教材示範用小表，實務常改 mini-batch。",
    "強化學習用狀態、動作、獎勵，Q-learning 更新 Q(s,a) ← Q(s,a)+α[r+γ max Q(s',a')−Q(s,a)]，γ 接近 1 會看重遠未來但收斂慢。",
    "ε-greedy 讓 agent 偶爾亂試，ε 退火太快會困在次優策略，太慢則線上系統會一直做危險探索。",
    "特徵工程把原始欄位變成模型能用的數字：類別做 one-hot、時間拆小時與星期、文字做詞頻或 TF-IDF。",
    "目標洩漏是把未來才知道的欄位當特徵，驗證集準確率會假高，上線立刻崩，例如用「結案後滿意度」預測「會不會投訴」。",
    "過擬合表現為訓練誤差低、驗證誤差高；正規化 L2、dropout、早停、加資料，都是在限制模型背答案。",
    "欠擬合是訓練誤差就高，該加特徵或換較有容量的模型，而不是先加 dropout。",
    "資料切分至少訓練／驗證／測試三份，測試集只碰一次；用測試集調超參數等於沒有測試集。",
    "時間序列不能隨機 shuffle 切分，否則未來資訊漏進訓練，應依時間切 last 20% 當測試。",
    "K 折交叉驗證在小資料穩，但每折都要重做特徵縮放，scaler 只能 fit 該折的訓練部分。",
    "分類輸出類別，指標用準確率會被多數類洗掉，要看 precision、recall、F1 與混淆矩陣。",
    "不平衡資料的召回率對少數類（詐欺、惡性腫瘤）通常比整體準確率重要，門檻 0.5 不一定該用。",
    "迴歸輸出連續值，RMSE 懲罰大誤差，MAE 較穩健；R² 接近 1 仍可能在業務單位上誤差不可接受。",
    "ROC 的 AUC 不依賴單一門檻，PR 曲線在正類極少時比 ROC 誠實。",
    "決策樹可讀規則，深度太大就背資料；隨機森林平均多棵樹降變異，但特徵重要性會偏向高基數類別。",
    "線性迴歸假設殘差大概獨立同分布，係數可解釋方向；共線特徵會讓係數符號不穩。",
    "邏輯斯迴歸輸出機率，權重是 log-odds；類別特徵沒做 dummy 就丟進去，實作函式庫可能默默當連續數。",
    "kNN 沒有顯式訓練，預測要算距離，特徵沒標準化則「薪水」會壓過「年齡」。",
    "SVM 的核函數把資料映射到高維，C 與 gamma 一亂調就過擬合，教材示範用小資料看邊界即可。",
    "神經網路一層是 y=f(Wx+b)，多層堆疊才叫深度；激活函數 ReLU 緩解梯度消失但仍可能 dying ReLU。",
    "反向傳播用鏈式法則把損失對權重的梯度傳回，學習率太大 loss 震盪，太小則訓練看似不動。",
    "批次梯度用全資料算一次更新，小批次 SGD 有雜訊但能逃出尖銳極小，batch size 要能放進 GPU 記憶體。",
    "CNN 用卷積核掃影像，權重共享讓同一邊緣偵測器在整張圖重複使用，參數遠少於全連接。",
    "池化 MaxPool 降空間尺寸，對微小平移較不敏感，但會丟掉精確位置，偵測定位任務常改用 stride convolution。",
    "影像增強 rotation、crop、色偏可減過擬合，醫療影像亂翻轉可能創造不存在的解剖方位，要看領域。",
    "RNN 把隱藏狀態當記憶往後傳，長序列梯度易消失；LSTM 用 forget/input/output gate 緩解，不是魔法無限記憶。",
    "LSTM 的 cell state 能把梯度傳得較遠，但對真正長文件仍弱，現在序列任務多改 Transformer。",
    "Transformer 的 self-attention 讓每個 token 對其他 token 算權重，Q、K、V 三個線性投影來自同一輸入。",
    "注意力權重 softmax(QK^T/√d_k)V，除以 √d_k 是避免點積過大讓 softmax 過尖、梯度過小。",
    "位置編碼把順序資訊加回，因為純注意力本身不認「誰在前」；沒有它，句子被打亂仍可能得到相似表示。",
    "ChatGPT 這類對話模型在解碼時一次產生下一個 token，temperature 高較多樣，接近 0 則幾乎總走最大機率路徑。",
    "top-p（nucleus）截斷低機率尾巴，比只調 temperature 更能避免怪異低頻詞突然出現。",
    "提示（prompt）要給任務、格式、約束與例子，空泛的「寫得好一點」無法當規格。",
    "few-shot 在提示裡放兩三個輸入輸出對，能鎖定格式，但例子本身帶偏見時模型會學偏。",
    "系統訊息與使用者訊息角色不同，把機密政策只寫在系統層仍可能被後續使用者誘導洩漏，不能當唯一防線。",
    "多輪對話要把必要上下文自己重貼或做摘要，模型視窗滿了會丟最早的約束，例如「一律用繁體中文」。",
    "幻覺是模型產生看起來合理但不在資料裡的事實，引用網址與數字都要外核對，不能當百科。",
    "瀏覽或外掛把即時網頁塞進上下文，來源錯誤會被模型寫得更肯定，仍要看原始頁。",
    "GPTs 自訂可上傳說明書與工具，知識檔沒更新時回答會過期，版本要當組態管理而不是一次設定永久正確。",
    "函式呼叫（tool calling）讓模型輸出 JSON 參數再由你的程式執行，參數驗證與權限必須在應用層做，模型不能直接擁有刪除權。",
    "DALL-E 類文生圖是條件生成，提示要寫主體、構圖、風格、負向約束；種子與尺寸影響再現性。",
    "影像模型會強化訓練集刻板印象，提示「醫師」若預設男性，要在規格裡要求多樣性並做抽樣檢查。",
    "語音轉文字的 WER 受口音與專有名詞影響，客服錄音要自訂詞表，不能直接把 transcript 當法律紀錄。",
    "文字轉語音的韻律與停頓靠標點與 SSML，教學朗讀若語速固定，長公式會聽不清楚。",
    "Copilot 類程式助手是統計補全，會建議過時 API 或不安全的 eval，合併前要跑測試與 code review。",
    "把整份專有程式庫貼進提示可能洩密，企業應走核准的外掛或自架模型，金鑰與程式碼不要進公開聊天。",
    "Python 呼叫雲端 API 用 requests.post，標頭放 Authorization: Bearer，timeout 與重試要寫，網路抖動不是模型壞掉。",
    "API 金鑰放環境變數或本機密鑰檔，.gitignore 要含 .env，誤 commit 後必須輪替金鑰而不能只刪檔。",
    "串流回應用 SSE 或 chunk 迭代印出 token，教學示範若等完整 JSON 才顯示，使用者會以為當機。",
    "token 計費依輸入加輸出，長系統提示每輪都重複計價，應把穩定說明放到可快取或縮短的段落。",
    "評測生成品質不能只看 BLEU 或「讀起來順」，應抽樣人工打正確、有害、偏離規格三個維度。",
    "自動指標 ROUGE 適合摘要重疊，對話任務要另設測試集問題與參考要點清單。",
    "資料集偏誤來自蒐集管道：網路論壇過代表某些人口，模型會把常見偏見複製成「常識」。",
    "標註者指令含糊會產生標籤噪音，監督學習再強也學到吵雜邊界。",
    "公平性檢查至少依敏感屬性切混淆矩陣，整體 F1 高但某一組召回低仍是缺陷。",
    "隱私攻擊包含訓練資料記憶，生成式模型可能吐出近似的個資字串，上線前做 canary 字串測試。",
    "倫理清單：誰受傷害、能否退出、決策能否解釋、出問題誰負責，客服機器人仍要有轉真人按鈕。",
    "台灣客服場景常見中英夾雜與地址格式，評估集要含郵遞區號、縣市鄉鎮，而非只有英文公開基準。",
    "教學應用可產生練習題，但答案必須另由題庫或教師核對，模型算錯分數卻講得很有自信。",
    "辦公室草稿可縮短會議紀錄，人名與決議要人工對出席名單，同音人名最容易張冠李戴。",
    "政府或學校個資不得未經評估送入境外 API，可改摘要後再問，或使用合約內的資料處理條款。",
    "傳統規則與模型可混成：先用正則抓身份證格式，再用模型分類意圖，全模型端到端不一定比較穩。",
    "專家系統在稅務法規這種需審計軌跡的領域仍有位置，生成模型負責起草，規則引擎負責硬約束。",
    "搜尋演算法考題要會畫 open/closed 集合，口頭說「AI 會找最短路」不算會 A*。",
    "感知機只能分線性可分資料，XOR 需要隱藏層，這是為什麼多層網路在教材裡出現的理由。",
    "softmax 把向量變成機率和為 1，分類交叉熵與它搭配；迴歸不該亂套 softmax。",
    "one-hot 標籤與 label smoothing 不同，後者避免模型對訓練標籤過度自信。",
    "學習率調度 cosine 或 step decay 常比固定 lr 穩，但教材實驗要先能過擬合一小撮樣本證明實作沒寫錯。",
    "BatchNorm 在訓練與推論的 moving average 不同，忘記 model.eval() 會讓驗證指標亂跳。",
    "資料增強太強等於換任務，OCR 亂旋轉 90 度可能讓模型去認倒字而不是內容。",
    "遷移學習凍結 CNN 前幾層、只訓分類頭，小影像集較不容易過擬合，但仍要檢查來源領域是否相近。",
    "目標偵測的 IoU 門檻影響 mAP，教材用分類準確率衡量偵測模型會講錯話。",
    "詞袋模型不管詞序，「不是」與「是不」向量相近，這是 RNN 與 Transformer 要解決的詞序問題。",
    "subword 如 BPE 讓罕見中文詞可拆，token 數影響價差與上下文窗，中文句子的 token 數通常多於直覺字數。",
    "embedding 餘弦相似度近不代表可替換，反義詞在某些空間也靠近，因為出現上下文類似。",
    "ChatGPT 多模態可看圖回答，圖中文字 OCR 仍會錯，發票辨識要對稅額加總而不是只信描述。",
    "上傳圖片可能含 EXIF GPS，送出前應剝 metadata，這是產品化而不是模型能力問題。",
    "語音對話的延遲來自 ASR、LLM、TTS 三段，優化要測各段 p95，而不是只換一個更大的語言模型。",
    "外掛瀏覽的引用列表要可點回，課堂作業若禁止上網仍去開瀏覽，等於換一種搜尋引擎作弊。",
    "GPTs 的 extra instructions 過長會擠掉使用者問題，應把穩定政策寫短、細節放知識檔並可檢索。",
    "檢索增強（RAG）先搜文件再生成，chunk 太大切不準、太碎沒上下文，重疊 10–20% 是常見起點。",
    "RAG 的引用必須來自檢索到的 chunk id，模型自己編的書名要當幻覺擋下。",
    "向量資料庫的距離度量要與 embedding 模型一致，用內積訓練的向量不要突然改歐氏距離。",
    "評估 RAG 用答案是否被 chunk 支持（faithfulness）以及問題是否找對文件（retrieval recall）。",
    "溫度與 top-p 同時開到極端，輸出會既亂又長，教學時一次只動一個超參數。",
    "stop sequence 可截斷模型繼續寫到使用者角色，聊天機器人忘記設 stop 會自問自答。",
    "max_tokens 太小會讓 JSON 輸出被截斷，下游 json.loads 失敗看起來像模型不會遵守格式。",
    "JSON mode 或 schema 約束能降低格式錯誤，仍要驗證必填欄位型別。",
    "單元測試可把固定提示與期望子字串寫死，模型一改版測試會紅，這是特性不是困擾，代表你有回歸網。",
    "A/B 測試線上文案生成要看點擊也要看客訴，順暢的錯答案傷害比笨拙的正確更大。",
    "人類抽樣每週固定 N 則，記錄嚴重等級，不要只在出事才翻聊天紀錄。",
    "提示注入是使用者在資料裡寫「忽略先前指令」，把不可信文件與系統政策隔離，工具權限最小化。",
    "越獄成功不代表你的應用必須接受該行為，產品層要拒絕並記錄，而不是跟著模型鬧。",
    "兒童與醫療等高風險場景，入門課的正確結論是「不要部署」，不是調一個更好的 prompt。",
    "著作權：生成圖可能近似訓練風格，商用前要看服務條款與是否允許再授權。",
    "開源權重與雲端 API 的差異在資料駐留、延遲、更新節奏，入門先把問題定義清楚再選。",
    "本機小模型可離線示範 softmax 與注意力，不必為了教材去打昂貴的長上下文。",
    "第四版會提到多模態與 GPTs，但梯度、切分、過擬合這些詞沒變，新按鈕不取代舊觀念。",
    "產品名稱與 UI 位置會改，作業應要求截圖當週介面並寫所用模型名稱，而不是抄舊版選單路徑。",
    "Chat Completions 與 Assistants 這類端點語意不同，範例程式不要混用 thread_id 與 messages 陣列。",
    "rate limit 的 429 要退避，教學程式用無限 while 重試會在金鑰洩漏時幫忙打爆帳單。",
    "帳單告警設用量上限，課堂共用金鑰是事故來源，應每人自備受限金鑰。",
    "log 不要印完整 prompt 若含個資，除錯用雜湊或截斷。",
    "requests 核對 HTTPS 憑證不要 verify=False，教室網路攔截 HTTPS 時應裝校方憑證而不是關掉驗證。",
    "pandas 讀 CSV 指定 encoding，Big5 與 UTF-8 混用會讓中文標籤變亂碼，模型看起來像學錯類別。",
    "訓練前看 df.describe 與缺失值，平均值填補對異常值敏感，類別缺失應設 unknown 而不是眾數瞎填。",
    "標準化 StandardScaler 有均值與方差，新資料要用同一組參數 transform，重新 fit 測試集是洩漏。",
    "混淆矩陣的列是真實、欄是預測或相反，報告前看函式庫文件，講反 precision 會整章錯。",
    "學習曲線橫軸是訓練集大小，若兩者誤差都高是欠擬合，中間有大缺口是過擬合。",
    "早停看驗證 loss，選驗證最佳那個 epoch 的權重，最後再在測試集報一次。",
    "隨機種子可再現作業，但單一種子的好成績可能運氣，重要結論要多種子。",
    "類別不均衡可用 class_weight 或重採樣，SMOTE 在高維稀疏文字上效果不穩，不要當萬靈。",
    "聚類沒有 y，不能用 accuracy；可用外部標籤當參考，或內部指標加人工看群代表點。",
    "PCA 降維便於畫 2D，解釋變異比例低時圖好看但不代表結構真實。",
    "關聯規則 support、confidence、lift，高 confidence 低 lift 可能只是因為後件本來就熱門。",
    "規劃與搜尋屬符號 AI，感知與語言多屬統計學習，第四版把兩條線都講，作業不要混成一句「都是 AI」。",
    "圖靈測試是行為判準，通過也不表示有理解，教材應用來討論評測困難而不是當產品 KPI。",
    "弱 AI 做特定任務，強 AI 尚非工程交付範圍，簡報不要把聊天機器人寫成通用智慧。",
    "資料標註預算往往大於模型 GPU，專案時程要先算標註，而不是先租最貴的加速卡。",
    "MLOps 入門至少：資料版本、模型版本、指標看板、回滾；筆記本裡「跑出 99%」無法重現就不算交付。",
    "實驗追蹤記錄超參數、資料雜湊、程式 commit，否則兩個禮拜後不知道哪個檔是最好的。",
    "推論量化 INT8 可加速，準確率可能掉，要在驗證集重測而不是只看速度表。",
    "邊緣裝置記憶體不夠時，知識蒸餾用大模型教小模型，學生仍要在目標硬體測延遲。",
    "對抗樣本在影像加微小擾動可讓 CNN 改判，安全關鍵系統不能只報乾淨測試集準確率。",
    "資料漂移上線後特徵分布變了，要監控輸入統計與輸出分布，而不是等客訴。",
    "概念漂移是 P(y|x) 變了，例如詐欺手法更新，舊標籤策略失效，需重新標註。",
    "人機協作預設模型起草、人類核准，介面要顯示不確定性，例如低機率時強制人工。",
    "客服機器人要設定意圖覆蓋不到時的問句澄清，連續兩次低信心就轉人。",
    "教學評量若用模型批改開放題，要公布評分規準並抽樣雙人核，避免學生被幻覺分數傷害。",
    "辦公室自動摘要會議前先取得參與者同意錄音，這是法規與倫理，不是模型參數。",
    "生成程式的授權相容性：模型輸出片段可能近似 GPL 程式碼，商用產品要掃描。",
    "入門實作順序：問題定義、資料、基準（規則或線性）、較複雜模型、誤差分析、倫理檢查。",
    "基準模型沒先做，直接上深度學習，你無法知道多出來的正確率值不值那筆電費。",
    "誤差分析抽 50 筆錯題分類：標籤錯、特徵不足、模型盲點、規格不清，再決定下一週做哪件事。",
    "ChatGPT 能解釋程式不代表執行過，作業要貼實際輸出與 assert 結果。",
    "把 API 範例改成函式並寫 docstring，金鑰從環境讀取，這才是「接 API 的程度」而不是在筆記本貼一整串秘密。",
    "第四版的正確學習目標是能區分搜尋、專家系統、三種學習、網路結構與生成式使用限制，而不是背最新產品發表會名詞。",
    "temperature 與 presence_penalty 一起加會讓用詞漂走，課堂報告應只記錄一個解碼參數與當次輸出。",
    "DALL-E 類負向提示寫 no text 仍可能出字，海報作業要用影像編輯二次去字而不是只靠提示。",
    "語音模型的採樣率 16 kHz 與 48 kHz 混接會失真，錄音前先固定格式再送 ASR。",
    "Copilot 建議的 SQL 字串拼接要改成參數化，否則教材示範會變成注入範本。",
    "人工抽樣表要含提示版本、模型名稱、溫度、是否開瀏覽，否則兩週後無法重現那則差的回答。",
]

HL53 = [
    "二進位 1011 當無號是 11，當 4 位二補數是 -5，同一位元樣式解釋權在程式設計師，CPU 不管你的註解。",
    "十六進位一個 nibble 對四個位元，0xFF 當 byte 無號 255、有號 -1，看 MOVZX 還是 MOVSX 決定延伸時填 0 或符號位。",
    "二補數取負就是 NOT 再加 1，-128 在 8 位沒有對應正數可表示，NEG 該值會設 OF。",
    "進位旗標 CF 管無號溢位，溢位旗標 OF 管有號溢位，JG 看 OF 與 SF、JA 看 CF 與 ZF，抄錯跳轉會讓有號比較走錯枝。",
    "AND 可用來清位元，OR 設位元，XOR 切換，XOR RAX,RAX 是常見清零且影響旗標。",
    "TEST 做 AND 但不寫回目的，常用 TEST RCX,RCX 再 JZ 判斷指標是否為空。",
    "SHL 邏輯左移，低位補 0，相當於無號乘 2；SAR 算術右移複製符號位，SHR 邏輯右移補 0。",
    "移位計數在 x86 用 CL 或立即值，移位次數對運算元寬度取模的細節要對指令手冊，不要假設 shift 64 次變 0。",
    "RAX 是 64 位累積器，EAX 是其低 32 位，寫 EAX 會把 RAX 高 32 位清零，這是 x86-64 的零延伸規則。",
    "AX、AH、AL 仍能用，但 AH 與 REX 前綴指令不相容的情況會讓組譯器報錯，新碼少碰 AH。",
    "RIP 是指令指標，相對定址 [rip+disp] 用來取 PIC 資料，LEAQ fmt(%rip), %rdi 是 System V 下印字串常見寫法。",
    "RFLAGS 裡 ZF、SF、CF、OF、PF、DF 最常考，CLD 清 DF 讓 MOVS 向高位址走，STD 反向，字串指令前要確定 DF。",
    "RSP 必須 16-byte 對齊才能呼叫 ABI 函式，CALL 會先 push 8-byte 回位址，因此函式開頭常再 SUB RSP,8 湊齊。",
    "RBP 可當框指標，序言 PUSH RBP; MOV RBP,RSP 後用 [rbp-8] 取區域變數，編譯器最佳化常省略 frame pointer。",
    "平坦模型下 CS/DS/SS 基址對使用者程式幾乎透明，段暫存器不再用 16 位 offset 拼 20 位實體位址那套 real mode。",
    "實模式 段*16+offset 會 wrap，保護模式靠描述子，教材若示範 INT 21h 那是 DOS，64 位 Windows 不能用。",
    "立即定址 MOV RAX,1 把常數編碼進指令；暫存器定址 MOV RBX,RAX；間接 MOV RAX,[RBX] 從記憶體載入。",
    "基址加變址 MOV EAX,[RBX+RSI*4] 的比例限 1、2、4、8，用來掃 dword 陣列，比例寫 3 組譯器不會接受。",
    "有效位址還可加位移 [RBX+RSI*4+8]，注意不要讓變址超出陣列，組合層沒有自動邊界檢查。",
    "MOV RAX,[addr] 讀記憶體內容，LEA RAX,[addr] 只計算位址不讀記憶體，取陣列元素指標用 LEA 而不是 MOV。",
    "LEA 也能做簡單算術 LEA RAX,[RBX+RBX*2] 得 3*RBX，不影響旗標，這點與 ADD 不同。",
    "ADD 影響 CF/OF/ZF/SF，INC 在部分編碼不影響 CF，迴圈計數若之後要依 CF 做 ADC 會踩坑，教材應用 ADD 1 較直觀。",
    "SUB 與 CMP 都做減法，CMP 不寫回目的只改旗標，條件跳轉前幾乎總是 CMP。",
    "IMUL 有號乘，單運算元形式把 RAX 乘記憶體，128 位結果在 RDX:RAX；截成 64 位前要看 OF。",
    "MUL 無號乘同樣用 RDX:RAX，與 IMUL 對負數結果不同，選錯指令符號會炸。",
    "IDIV 有號除前要 CQO 把 RAX 符號延伸到 RDX，否則高位當亂數，除以 -1 且被除數是最負值可能例外。",
    "DIV 無號除用 XOR RDX,RDX 清高位，誤用 CQO 會把無號大數當成負數。",
    "除零與溢位會觸發 #DE，除錯時 gdb 會停在 IDIV，先印 RDX:RAX 與除數。",
    "ADC 帶進位加，用在多精度；SBB 帶借位減，大數運算要從低位字到高位字串起來。",
    "NEG 取二補數，對 0 結果仍 0 且 CF 的定義要查手冊，測旗標作業別只測正數。",
    "NOT 是一補數不影響旗標，和 NEG 不同，清旗標請用別的指令。",
    "條件跳轉 JE/JZ 看 ZF，JNE 看 ZF=0，JL 是有號小於（SF≠OF），JB 是無號低於（CF=1）。",
    "JCC 的短跳位移是 8 位，目標太遠要近跳轉或用近 JCC 的 near 形式，組譯器通常會自動選。",
    "LOOP 用 RCX 當計數器，每圈減 1 直到 0，現代 CPU 上 LOOP 常比 DEC RCX; JNZ 慢，編譯器幾乎不用 LOOP。",
    "REP MOVSB 依 RCX 與 RSI/RDI 搬區塊，方向看 DF，重疊記憶體要用 memmove 語意小心方向。",
    "CALL 把回傳位址 push 進堆疊並跳到目標，RET  pop 到 RIP，CALL/RET 不成對就會跳到資料當指令。",
    "NEAR RET 只 pop RIP，RET n 還會加 ESP/RSP 丟掉 stdcall 的堆疊參數，x64 微軟慣例參數多半不靠這種清法。",
    "Microsoft x64 前四個整數參數在 RCX、RDX、R8、R9，浮點在 XMM0–XMM3，其餘進堆疊，呼叫端還要預留 32-byte shadow space。",
    "System V AMD64 整數參數 RDI、RSI、RDX、RCX、R8、R9，沒有 shadow space，紅區 128 bytes 在 RSP 下方可被訊號踩，葉函式仍要小心。",
    "Windows x64 非揮發暫存器含 RBX、RBP、RDI、RSI、R12–R15，函式要用就要自己 push/pop 保存。",
    "System V 的 RBX、RBP、R12–R15 屬 callee-saved，RDI 是參數所以是 caller-saved，移植組合模組時保存清單不能照抄 Windows。",
    "浮點參數與返回在 XMM，混用整數與 double 時第 n 個參數的暫存器編號依慣例計數方式，要對 ABI 文件畫表。",
    "區域變數 SUB RSP,32 後用 [rsp+offset] 存，離開前 ADD RSP,32，中間若有 CALL 仍要維持對齊。",
    "堆疊向低位址成長，buffer 宣告在高 offset、回位址在更深（較高位址）處，gets 式寫入向高位址溢位會蓋 RET。",
    "緩衝區溢位在組合層就是 MOV 迴圈沒比長度，RBP 與 RIP 相繼被蓋，gdb 看 x/32gx $rsp 能看見假回位址。",
    "金絲雀（stack cookie）由編譯器在回位址前插入，手寫組合若自己開緩衝區通常沒有 cookie，更要顯式檢查長度。",
    "系統呼叫在 Linux x64 用 syscall，號碼在 RAX，參數 RDI/RSI/RDX…，返回負錯誤碼在 RAX，與 libc 的 errno 包裝不同。",
    "Windows 使用者態少直接 syscall，多 CALL 到 kernel32/ntdll，教材若寫 INT 0x80 那是舊 Linux i386。",
    "NASM 的 MOV rax, [rbx] 與 MASM 的 QWORD PTR 標註風格不同，NASM 預設大小常靠暫存器推斷。",
    "NASM 區段 .text/.data，MASM 用 .code/.data 與 PROC ENDP，標籤在 NASM 要 global main 才能給連結器。",
    "GAS AT&T 語法來源在右 MOV %rbx,%rax 是 rbx→rax，與 Intel 相反，讀 objdump 預設 AT&T 時別把運算元看反。",
    "組譯 nasm -f win64 或 -f elf64 產生目的檔，再由 link 或 ld 加 CRT 進入口，缺 main 或 WinMain 會 LNK2019。",
    "除錯 gdb 用 break *_start、info registers、si、x/i $rip，Windows 則用 Visual Studio 反組譯視窗看 RIP 與旗標。",
    "gdb 的 tui 可同時看暫存器，條件跳轉後用 p $eflags 不如 info r eflags 清楚，作業應印 ZF 是否符合 CMP 預期。",
    "Visual Studio 要關最佳化並開 /Zi，否則 C 行號與組合對不上，你會以為 ADD 被吃掉其實是常數折疊。",
    "中斷 INT n 在舊模式進 IDT，64 位使用者程式不該拿來當 API；例外如 #PF、#DE 由 OS 處理。",
    "除錯例外 INT3 編碼 0xCC，下斷點就是把指令第一個位元組改成 CC，繼續執行要還原。",
    "SIMD 的 XMM0–XMM15 做 SSE，MOVAPS 要求 16-byte 對齊，未對齊用 MOVUPS，對齊錯會 #GP。",
    "ADDPS 一次加四個 float，純量迴圈改 SIMD 要處理尾巴元素與對齊，編譯器自動向量化常比手寫完整。",
    "MXCSR 控制浮點捨入與例外遮罩，手改前先讀現值，教學作業亂 unmask 會讓正常 underflow 變例外。",
    "與 C 互操作：組合檔 global foo，C 端 extern long foo(long)；名稱修飾在 C 沒有，C++ 要 extern \"C\"。",
    "呼叫 C 的 printf 前要對齊 RSP 並依 ABI 放參數，漏 shadow space 在 Windows 上可能看起來能跑直到校準函式炸掉。",
    "從 C 傳陣列進來是指標，組合裡當位址不是值，第一個元素是 [rcx] 在 Microsoft x64。",
    "結構對齊與 padding 要跟 C 編譯器一致，手算 offset 錯會讓欄位讀到隔壁。",
    "volatile 在 C 阻止優化掉對記憶體的存取，對 MMIO 有意義；純暫存器運算不需要。",
    "編譯器常贏手寫是因為指令排程、暫存器配置、內建 memcpy、自動 SIMD，微觀少一條 MOV 不敵整函式最佳化。",
    "手寫組合的合理用途是看編譯器輸出、寫啟動碼、或量測已知熱點，而不是重寫整個應用。",
    "用 gcc -O2 -S 看 C 變成哪些指令，對照自己寫的 ADD 迴圈，常會發現編譯器用 LEA 與定址模式合併了三步。",
    "旗標學習路徑：寫一段 CMP RAX,RBX 後用條件設定指令 CMOVG 或 SETG，再在 gdb 改 RAX 測邊界 0、最大正、最小負。",
    "SETCC 把條件寫進 byte，要 MOVZX 成 32/64 位再當整數用，否則高位垃圾會污染。",
    "CMOV 不跳轉，有助於避免分支預測失誤，但兩路都要準備好運算元，語意與 if 不完全一樣。",
    "無條件 JMP 可做迴圈或 switch 跳表，跳表項必須是代碼位址，資料被當成 JMP 目標即控制流劫持。",
    "間接 CALL [table+rax*8] 是函式指標，ROP 攻擊也靠 ret 到小片段，理解 RET 吃堆疊就能理解為何溢位危險。",
    "NX/DEP 讓堆疊不可執行，溢位改 RIP 仍可能改去已存在的 libc gadget，所以還有 ASLR 與 cookie。",
    "ASLR 讓模組基址每次不同，[rip+disp] 相對定址仍正確，寫死絕對位址的 shellcode 教材在現代 OS 會失效。",
    "位元欄位用 AND 遮罩再 SHR 取出，硬體暫存器驅動常用這招，移位數量要註解對應規格書 bit index。",
    "BTx 測位元、BTS 設位、BTR 清位，可對記憶體原子性較佳的情境，仍要注意快取行。",
    "LOCK 前綴讓讀改寫對匯流排原子，LOCK INC [counter] 是最簡單的共享計數，漏 LOCK 在多核會少算。",
    "XCHG 預設有 lock 語意，常用來做自旋，忙碌迴圈要 pause 減緩管線壓力。",
    "CPUID 用 EAX 功能號，回傳在 EAX/EBX/ECX/EDX，偵測 SSE4/AVX 再決定是否走向量路徑。",
    "RDTSC 讀時間戳，亂序執行下要加 lfence/rdtscp，作業測量不能只包兩條 RDTSC 就宣稱週期數。",
    "對齊：資料 .align 8 或 align 16，未對齊的 MOV [rax] 在舊架構罰週期，SSE 對齊更嚴。",
    "小端序低位元組在低位址，DWORD 0x12345678 在記憶體是 78 56 34 12，用 gdb x/4xb 核對。",
    "大端協定（網路）要用 BSWAP 或 MOVBE，直接把 uint32 當 IP 位址會顛倒。",
    "符號延伸 MOVSX EAX,BYTE PTR [rsi] 把 0xFF 變成 0xFFFFFFFF，無號資料該用 MOVZX。",
    "32 位作業系統上的組合與 64 位暫存器不能混，WOW64 有自己的呼叫慣例，教材要鎖定 --target。",
    "進入點 _start 沒有 CRT 時，結束行程在 Linux 用 SYS_exit，忘了 exit 會從 .text 落到垃圾繼續執行。",
    "Windows 的 subsystem 分 CONSOLE 與 WINDOWS，連結錯了會沒有主控台或 WinMain 對不上。",
    "MASM INVOKE 幫你排參數，手寫 CALL 時漏一個 push 會讓後續區域變數全錯位。",
    "NASM 的 EQU 與 %define 是組譯期常數，不是執行期變數，改 EQU 不會佔記憶體。",
    "times 256 db 0 可清 BSS 風格緩衝，.bss 不佔目的檔大小但佔執行期記憶體。",
    "字串 db 'hello',0 記得 NUL，呼叫 C 字串函式缺 0 會讀到後面資料。",
    "Unicode 在 Windows 常是 UTF-16LE，WORD 字元，strlen 等價函式要用寬字版，混用 byte 指令會切一半碼元。",
    "條件組譯 %ifdef WIN64 可切 ABI，同一份原始碼兩套參數暫存器，漏測 Linux 路徑很常見。",
    "目的檔重定位：對外部符號的 CALL 在連結前是 stub，objdump -d 在 .o 與最終 exe 看到的位移不同。",
    "靜態連結把函式碼 copy 進 exe，動態連結留下 PLT/IAT，除錯時 call 先到 trampoline 再去真正 printf。",
    "IAT 被改寫是惡意程式手法，理解組合才能在 debugger 看出 JMP 不是進 kernel32 原位。",
    "例外處理 SEH 在 Windows 堆疊上有 EXCEPTION_REGISTRATION，手寫破壞 RSP 可能讓 debugger 也無法漂亮展開。",
    "Linux 的 DWARF unwind 資訊讓 gdb backtrace 成功，手寫組語沒 .cfi 時 bt 會亂，但不影響正確 RET。",
    "系統呼叫錯誤回傳 -errno，比較要用有號 JG，當成無號會把錯誤當成超大成功值。",
    "errno 在 libc 是 thread local，純 syscall 迴圈沒有 errno，要把 RAX 自己轉成錯誤碼。",
    "記憶體對齊 malloc 通常 16-byte，SSE 載入自訂緩衝仍應 posix_memalign，堆上不一定對齊 32。",
    "page fault 在存取未 map 頁時發生，教材寫超大 [rax] 若 rax 是 0 就是空指標解參考。",
    "保護：使用者態不能 in/out 碰 I/O 埠，那是 ring 0，課堂說的 port mapped I/O 在應用程式會 #GP。",
    "特權指令 CLI/STI 關中斷只在核心，使用者組合練習不該出現，除非作業是寫 OS。",
    "CR3 存頁表基址，應用程式作業看不到，虛擬位址翻譯是 OS 與硬體的事，平坦模型仍有分頁。",
    "TLB 快取虛擬到實體翻譯，改頁表要 invlpg 或 CR3 重載，這是 OS 課延伸，應用只需知道為什麼大陣列跳動慢。",
    "快取行 64 bytes，連續 MOV 掃陣列比跳躍 stride 快，手寫最佳化先看資料區域性再看指令數。",
    "false sharing 兩個核心改同一 64-byte 行的不同變數，LOCK INC 會互相使快取無效，計數器要 padding。",
    "分支預測：CMP 後幾乎總成立的迴圈很友善，資料相關的隨機 JE 會讓 CPU 前端停滯，這是編譯器插 CMOV 的理由之一。",
    "指令快取 I-cache 喜歡小熱迴圈，把巨大 switch 展開可能反而較慢。",
    "自我修改程式碼改即將執行的位元組要同步管線，現代 CPU 與 NX 都不歡迎，除錯器斷點是少數合法案例。",
    "PIC 位置無關碼用 RIP 相對，共用函式庫必須 PIC，絕對 MOV rax, imm64 塞位址在 so 裡會 relocation 爆炸。",
    "大立即數 MOV RAX, imm64 是 10-byte 指令，常用小常數用 32 位立即零延伸較短。",
    "NOP 多位元組長度用來對齊迴圈入口到 16-byte，編譯器會插多位元組 NOP，不是當機。",
    "UD2 是明確未定義指令，常用來標「不可達」，走到這就該崩潰。",
    "INT1/ICEBP 是除錯用，不要當一般 ABI。",
    "RDRAND 取硬體亂數，失敗要看 CF，教材示範仍應處理失敗路徑。",
    "AESENC 等 AES-NI 是特殊指令，手寫加密前要 CPUID 檢查，否則 #UD。",
    "系統 V 紅區讓葉函式不 SUB RSP 也能用 [rsp-8]，一 CALL 出去紅區可能被訊號處理蓋掉。",
    "Windows 沒有紅區，葉函式仍常 SUB RSP 以對齊並留 shadow。",
    "vararg 函式如 printf 在 Microsoft x64 要把浮點同時複製到整數暫存器，漏了印 double 會錯。",
    "home space 32 bytes 是被呼叫者可把 RCX 等 spill 到 [rsp+8] 那塊，呼叫端必須配置即使你用不到。",
    "巢狀 CALL 每層對齊一次，中間 PUSH 奇數個 8-byte 會破壞 16-byte 對齊，XMM 相關函式特別敏感。",
    "保存 XMM6–XMM15 在 Windows 是 callee-saved 的一部分，手寫用到 XMM6 要存回，System V 則多半 caller-saved。",
    "這就是為何「同一段 SSE 組合」不能在 Win/Linux 之間只改組譯格式就拿去連結。",
    "學習驗證：寫 add64 函式，C 測 0、1、-1、0x7FFFFFFFFFFFFFFF、溢位案例，並在組合裡用 SETO 回傳是否溢位。",
    "再寫 strcmp 風格迴圈，用 CMPSB 或自行 LODSB，對空字串、長度 1、差在最後一 byte 三組測。",
    "memcpy 對齊到 8 後用 MOV RCX 次數，尾巴用 byte，再用 gdb 看目的緩衝是否越界寫到 canary。",
    "乘法作業同時印 IMUL 的 RDX:RAX 與 OF，對 0x8000000000000000 這種邊界特別測。",
    "除法作業測除數 1、-1、2，被除數最負，預期 #DE 時要在除錯器看到例外而不是默默錯答案。",
    "旗標表自己畫：CMP 5,5 ZF=1；CMP 5,7 SF 與有號關係；CMP 無號 5,7 CF=1，把 JE/JL/JB 各走一遍。",
    "把 C 的 for(i=0;i<n;i++) a[i]+=1 編成 INC 迴圈與 SIMD 兩版，用 rdtsc 比，理解為何編譯器 -O3 常接近 SIMD 版。",
    "閱讀 objdump 時認 opcode 89 是 MOV r/m,r，8B 是反向，比只認助記符更能查編碼手冊。",
    "ModR/M 與 SIB 位元組決定定址模式，這是 [rbx+rsi*4] 為什麼能編進指令的硬體理由。",
    "REX.W 把運算從 32 改 64 位，沒有 REX 的 ADD eax,1 與 ADD rax,1 編碼長度不同。",
    "作業繳交應附：原始組語、組譯連結指令、gdb 或 VS 截圖暫存器、以及用 C 測試主程式的輸出。",
    "先正確再談週期，錯誤的快速迴圈只是快速得到錯的旗標。",
    "ENTER 指令把 RBP 框起來並 SUB 區域空間，LEAVE 還原，手寫可用它對照編譯器序言，但 x64 編譯器仍常手寫 push rbp。",
    "PUSHFQ/POPFQ 保存 RFLAGS，中間夾雜算術會改旗標，巢狀計算前若要記住 ZF 應先 SETZ 到暫存而不是事後猜。",
    "CBW/CWDE/CDQE 依序把 AL 延伸到 AX、EAX、RAX，IDIV 前選錯延伸寬度等於把垃圾當高半部。",
    "XADD 交換並相加，可做 lock xadd 的 fetch-and-add，教材用它解釋原子計數比純 INC 更完整。",
    "CMPXCHG 把 EAX 與記憶體比較相等才寫入新值，是 CAS 的硬體原語，自旋鎖作業應印 ZF 判斷是否成功。",
    "BSF/BSR 找最低或最高置位，回傳 index 且來源為 0 時 ZF=1，掃 bitset 前要處理空集合。",
    "POPCNT 數 1 的個數，實作漢明距離可 XOR 後 POPCNT，仍要用 CPUID 確認支援。",
    "PREFETCHT0 提示快取，亂預取會擠掉有用行，量測時對照有無 prefetch 的 rdtscp 差距再下結論。",
    "LFENCE/SFENCE/MFENCE 管記憶體可見性，x86 一般 store 已有相當強保證，但 DMA 或 WC 記憶體才需要明確圍籬。",
    "VZEROUPPER 在 AVX 與 SSE 混用後避免 state transition 懲罰，手寫 AVX 函式返回前常要加。",
    "YMM 是 XMM 的延伸，編譯器在 Windows x64 對 YMM6 以上也有保存規則，亂用 ymm 破壞 C 呼叫端狀態。",
    "syscall 後 RCX 與 R11 被硬體改寫（RIP 與 RFLAGS 備份），Linux 組語不要假設 RCX 在 syscall 後仍是參數。",
]


def validate(bodies: list[str], label: str) -> list[str]:
    assert len(bodies) == 150, f"{label} count={len(bodies)}"
    texts = []
    for i, b in enumerate(bodies, 1):
        assert PIPE not in b, f"{label} {i} has pipe"
        for ban in BANNED:
            assert ban not in b, f"{label} {i} banned {ban}"
        assert "面第" not in b, f"{label} {i} 面第"
        s = b.strip()
        assert s, f"{label} {i} empty"
        assert not s.startswith("00"), f"{label} {i} numbered in body"
        texts.append(s)
    cores = [COLON_TAIL.sub("", t) for t in texts]
    assert len(set(texts)) == 150, f"{label} duplicate full"
    assert len(set(cores)) == 150, f"{label} duplicate core"
    return [f"{i:03d}、{t}" for i, t in enumerate(texts, 1)]


def write_book(path: Path, bodies: list[str]) -> None:
    data = json.loads(path.read_text(encoding="utf-8"))
    hls = validate(bodies, path.name)
    data["chatgptHighlights"] = hls
    data["chatgptStatus"] = "complete"
    data["highlightsSource"] = "grok"
    data["highlightsCapturedAt"] = STAMP
    data["updatedAt"] = UPDATED
    text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    path.write_text(text, encoding="utf-8")
    loaded = json.loads(path.read_text(encoding="utf-8"))
    assert len(loaded["chatgptHighlights"]) == 150
    assert loaded["chatgptHighlights"][0].startswith("001、")
    assert loaded["chatgptHighlights"][-1].startswith("150、")
    assert loaded["highlightsSource"] == "grok"
    print(path, 150, loaded["highlightsSource"], loaded["highlightsCapturedAt"])


def main() -> None:
    write_book(ROOT / r"Books\06_computer_info\06_computer_info-20260716-51.json", HL51)
    write_book(ROOT / r"Books\06_computer_info\06_computer_info-20260716-52.json", HL52)
    write_book(ROOT / r"Books\06_computer_info\06_computer_info-20260716-53.json", HL53)


if __name__ == "__main__":
    main()
