# -*- coding: utf-8 -*-
"""Rewrite chatgptHighlights for 06_computer_info-20260716-44 and -45."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(r"C:\Users\johso\OneDrive\Desktop\Johsok_BookReading\Books\06_computer_info")
STAMP = "2026-08-18T09:10:00+08:00"
BANNED = ("本書", "作者指出", "本章", "這一章", "｜")
CHAP_RE = re.compile(r"第[一二三四五六七八九十0-9]+章")
STEP_RE = re.compile(r".面第\d+步")

H44 = [
    "Visual Studio 新增 Windows Forms App (.NET Framework) 時，專案名稱必須與術科指定字串逐字相同，評分以資料夾與 .csproj 檔名核對。",
    "組態管理員把平台目標設成 Any CPU，鎖成 x86 會讓評分機以 64 位元開啟時無法載入組件。",
    "Form 的 Text 改成題目視窗標題例如「停車費計算」，Name 維持 Form1；只改檔名當標題會被判未設定。",
    "保留方案產生的 namespace，例如 namespace PayCalc，改成 Form1 或 WindowsFormsApp1 會扣命名空間不符。",
    "Button 的 Name 用 btnCalc、Text 用「計算」，設計工具產生的 btnCalc_Click 必須與 Click 訂閱一致，手動改名卻沒改 Designer 會編譯失敗。",
    "讀 TextBox 先 txtHours.Text.Trim()，空字串丟給 int.Parse 會 FormatException，空白未處理是術科高頻扣分。",
    "整數用 int.TryParse(txtQty.Text.Trim(), out int qty)，失敗就 MessageBox.Show(\"請輸入整數\") 並 return，不要讓程式崩潰。",
    "金額、稅額、薪資用 decimal，寫 double hours * 150.5 會累積二進位誤差，四捨五入後差 0.01 即輸出不符。",
    "小數兩位且四捨五入用 Math.Round(value, 2, MidpointRounding.AwayFromZero)；省略第三參數會用 ToEven，1.225 變成 1.22。",
    "字面常數 0.05m 的 m 不可省，否則 0.05 是 double，與 decimal 相乘要顯式轉換才過編譯。",
    "bool 判斷會員價讀 chkMember.Checked，不要用 CheckBox.Text == \"是\"，題目改顯示文字就會算錯。",
    "DateTimePicker 的 Value 是 DateTime，停車時數用 (dtpOut.Value - dtpIn.Value).TotalHours，不要把 Value.ToString() 當數字。",
    "lblResult.Text 金額格式用 ToString(\"0.00\") 對樣張；\"C\" 會依系統文化加上貨幣符號，評分字串會對不上。",
    "區域變數用 camelCase 如 overtimeHours，控制項用前綴 txt、btn、lbl、cbo、dtp，int a、string s 在學科選項屬不良命名。",
    "const decimal TaxRate = 0.05m 集中稅率，題目改 5% 只改常數，散落 0.05m 容易漏改一處。",
    "字串忽略大小寫用 string.Equals(input, \"Y\", StringComparison.OrdinalIgnoreCase)，寫 == \"y\" 會漏掉大寫。",
    "運算子 * / 優先於 + -，稅後價 amount * 0.05m + fee 與 amount * (0.05m + fee) 不同，先列輸入輸出表再加括號。",
    "整數除法 5 / 2 結果是 2，學科常考；要小數寫 5.0 / 2 或 (double)hours / 60。",
    "取餘 % 判偶數 n % 2 == 0、閏年 year % 4 == 0；負數餘數符號跟被除數，不要拿來當金額小數。",
    "&& 由左短路：qty > 0 && total / qty 在 qty 為 0 時不執行除法；寫成 total / qty > 10 && qty > 0 會 DivideByZeroException。",
    "條件運算 (score >= 60) ? \"及格\" : \"不及格\" 優先序低，外層務必加括號再接到字串串接。",
    "計算開頭擋空值：if (txtName.Text.Trim() == \"\") { MessageBox.Show(\"姓名不可空白\"); return; }。",
    "成績等第 if/else if 由高到低：>=90、>=80、>=70、>=60，順序顛倒會讓 95 分落入第一個真條件變成乙等。",
    "switch (cboLevel.Text) 每個 case 結尾 break，漏 break 會貫穿到下一費率，會員價變成一般價再加成。",
    "C# switch 不能寫 case >= 10，停車累進費率仍用 if (hours <= 1) else if (hours <= 3)，硬套 switch 無法編譯。",
    "ComboBox DropDownStyle 設 DropDownList，SelectedIndex == -1 表示未選，計算前 return 並提示「請選擇等級」。",
    "cboType.Items.Add(\"一般\") 與 Items.Add(\"會員\") 放在 Form1_Load，不要每次 Click 重複 Add 造成清單膨脹。",
    "RadioButton 必須放同一 GroupBox 才互斥，rdoHourly.Checked 與 rdoMonthly.Checked 分屬兩個容器會同時為 true。",
    "for (int i = 0; i < scores.Length; i++) 上限用 Length，寫 i <= scores.Length 會在最後一圈 IndexOutOfRangeException。",
    "次數未知的讀檔用 while ((line = sr.ReadLine()) != null)，已知筆數的加總用 for，兩者混用容易略過最後一列。",
    "foreach (string row in lines) 迴圈內不可 list.Remove(row)，要刪除先記下索引再從 Count-1 往 0 的 for。",
    "decimal sum = 0m 宣告在迴圈外；寫在 for 區塊內每次歸零，總計永遠等於最後一筆。",
    "break 離開最內層迴圈，continue 跳過本圈後續；找第一筆不及格用 break，統計全部不及格不該 break。",
    "int[] arr = new int[5] 合法索引 0 到 4，題目「第 1 筆」對應 arr[0]，顯示編號用 (i + 1)。",
    "Array.Sort(scores) 後最高分 scores[scores.Length - 1]、最低分 scores[0]，自己寫錯邊界常少算一筆。",
    "筆數不固定用 List<decimal> amounts = new List<decimal>(); amounts.Add(parsed); 不要先 new decimal[100] 浪費且難估上限。",
    "list.Count 為元素數，最後一筆 list[list.Count - 1]；Count == 0 時取索引會 ArgumentOutOfRangeException。",
    "list.Clear() 在重新讀檔前呼叫，否則第二次開啟 CSV 會把舊列疊在 DataGridView 下面。",
    "string[] parts = line.Split(','); 立刻 parts[i] = parts[i].Trim(); 欄位前後空白會讓 decimal.Parse 失敗。",
    "Split 後若 parts.Length < 題目欄位數，記錄列號並跳過，直接 parts[3] 會炸例外中斷整批匯入。",
    "Substring(0, 2) 取發票字軌前先 if (no.Length < 2) 提示格式，長度 0 會 ArgumentOutOfRangeException。",
    "Replace(\" \", \"\") 去掉身分證空格後檢查 Length == 10；PadLeft(8, '0') 把訂單編號補成樣張的 8 碼。",
    "PadRight(10, ' ') 對齊固定寬度文字檔，與 PadLeft 補零用途不同，題目要靠左空白就不要用 '0'。",
    "Contains(\"@\") 只能粗檢電子郵件，術科若只要非空與含 @，不要自行實作完整 RFC 驗證浪費時間。",
    "IndexOf(',') 找第一個逗號，LastIndexOf 找路徑最後反斜線；找不到回傳 -1，不可當 Substring 起點。",
    "ToString(\"000\") 把整數編成三位數編號，ToString(\"N2\") 含千分位逗號，樣張沒有逗號就禁用 N2。",
    "輸出日期字串用 ToString(\"yyyy/MM/dd\")，與 \"yyyy-MM-dd\" 差一個字元即格式不符，對題目樣張逐字元抄。",
    "int.Parse 遇到 12.0 會失敗，小數欄位用 decimal.Parse 或 decimal.TryParse，再 Math.Round 到指定位數。",
    "Convert.ToInt32 對 null 回 0、對小數會四捨五入，與 int.Parse 行為不同，術科金額欄不要混用。",
    "private decimal CalcFee(double hours) 把費率表集中，Click 只負責讀控制項、呼叫、寫 Label，方便設中斷點。",
    "方法參數是值傳遞，CalcFee 內改 hours 不影響呼叫端；要回傳稅額用 out decimal tax 或回傳元組。",
    "多載 CalcFee(int hours) 與 CalcFee(decimal hours, bool member) 依題目費率分支，避免單一方法十層 if。",
    "事件處理常式簽名必須 object sender, EventArgs e，自行刪參數會與 Designer 委派不符而編譯失敗。",
    "try { decimal n = decimal.Parse(txt.Text); } catch (FormatException) { MessageBox.Show(\"請輸入數字\"); return; } 先抓具體例外。",
    "catch (Exception ex) { MessageBox.Show(ex.Message); } 放最後當保險，不要只 catch Exception 導致檔案錯誤與格式錯誤同一句。",
    "using (StreamReader sr = new StreamReader(path, Encoding.UTF8)) 離開區塊自動 Dispose，漏關檔會造成第二次開啟分享違規。",
    "OpenFileDialog 的 Filter 寫成 CSV 與 *.csv 兩段，ShowDialog() == DialogResult.OK 才讀 FileName，按取消不得清空畫面。",
    "SaveFileDialog DefaultExt 設 csv、OverwritePrompt 為 true，確定後 new StreamWriter(path, false, Encoding.UTF8) 覆寫而非 Append。",
    "Encoding.UTF8 寫出的檔若題目指定，不要改 Big5；評分機讀 UTF-8 時 Big5 會變成亂碼欄位對不齊。",
    "StreamWriter 每列寫完 WriteLine，最後一筆也要換行，少換行會讓評分腳本少讀一筆。",
    "讀 CSV 跳過標題列：第一圈 ReadLine 丟棄或 if (lineNo == 0) continue，標題當數字 Parse 會整批失敗。",
    "寫 CSV 標題先 WriteLine(\"姓名,時數,薪資\")，欄位順序與題目樣張一致，中英逗號混用會少一欄。",
    "欄位內若可能有逗號，丙級題通常保證沒有；自行加雙引號包裹反而與樣張不符。",
    "DataGridView 用 Rows.Clear() 再 Rows.Add(name, hours, pay.ToString(\"0.00\"))，不要用 Items 那是 ListBox 的。",
    "欄位 DefaultCellStyle.Format 設 0.00 只影響顯示，Cell.Value 仍應是 decimal，計算不要從格式化字串 Parse 回來。",
    "AllowUserToAddRows 設 false，避免底部幽靈列被當成一筆空資料寫進檔案。",
    "dgv.CurrentRow 在無列時是 null，刪除鈕先判斷 Rows.Count 與 CurrentRow != null。",
    "Label AutoSize 可 true，但金額 lblPay 建議固定寬度並 TextAlign 靠右，避免位數變多把按鈕擠走。",
    "TextBox 的 MaxLength 設 10 限制身分證，PasswordChar 術科少用；ReadOnly true 給結果欄以免考生改輸出。",
    "Numeric 輸入可設 KeyPress 只允許數字與一個小數點，但仍要 TryParse，貼上 Ctrl+V 會繞過 KeyPress。",
    "進場離場控制項 Format 改 Custom、CustomFormat 設 yyyy/MM/dd，與題目日期字串一致，長日期會多出星期。",
    "ShowCheckBox 為 true 時，Checked 為 false 代表未指定日期，不可把 1899 或最小值拿去算停車。",
    "MessageBox.Show(msg, \"錯誤\", MessageBoxButtons.OK, MessageBoxIcon.Warning) 標題與圖示要對樣張，只有文字也常給分但標題不符會扣。",
    "詢問覆寫用 MessageBoxButtons.YesNo，DialogResult.Yes 才寫檔，把 OKCancel 當 YesNo 會讓取消語意相反。",
    "Form Load 裡還原上次路徑或填預設費率，不要在建構函式 Form1() 讀檔，設計檢視會執行建構式而炸掉。",
    "SelectedIndexChanged 裡改 TextBox 若又觸發 TextChanged 形成遞迴，用 bool _updating 旗標擋住重入。",
    "Click 計算時把焦點 txtName.Focus() 方便連續輸入，但 ShowDialog 之後焦點可能留在訊息框，要重設。",
    "AcceptButton 設 btnCalc，Enter 鍵等於按計算；CancelButton 設 btnClear，Esc 清空，勿與對話框衝突。",
    "TabIndex 依輸入順序 0,1,2…，TabStop false 給純顯示 Label，評分不一定查，但監評現場操作會看流暢度。",
    "Enabled = false 讓未選檔前 btnSave 不能按，避免 FileName 空字串去 new StreamWriter。",
    "Visible = false 隱藏進階欄位可以，但題目要求顯示的控制項不可藏，截圖與現場操作都要看得到。",
    "Anchor 設 Right 可讓視窗拉大時按鈕貼齊，術科視窗通常固定 Size 且 MaximizeBox false、FormBorderStyle FixedSingle。",
    "StartPosition 設 CenterScreen，不要依賴開發機解析度，評分機 1024×768 時視窗超出會被看成版面錯誤。",
    "Font 用題目指定新細明體 12，不要用開發機的 Segoe UI，中文標籤在評分機可能變方塊或跑版。",
    "學科：值型別 int、double、decimal、bool、DateTime 在堆疊，string 是參考型別，== 對字串比內容、對自訂類別比參考。",
    "string 不可變，s.Replace(\"a\",\"b\") 必須接回變數，只呼叫 Replace 不賦值，原字串不變。",
    "StringBuilder 適合迴圈內大量串接輸出檔，術科列數少用 + 即可，不必為兩行列引入新語法冒險。",
    "char 用單引號 '0'，字串用雙引號 \"0\"，PadLeft 第二參數是 char，傳 \"0\" 會編譯錯誤。",
    "nullable 丙級少考，int.Parse 失敗不是 null 而是例外；空 TextBox 是 \"\" 不是 null，Trim 後長度 0。",
    "var 推斷仍是強型別，var x = 3; 是 int，之後不能 x = 3.5；術科為求清楚可顯式寫 decimal pay。",
    "列舉 DialogResult.OK 與 1 不要混比，ShowDialog 回傳列舉，寫 == 1 在學科算不良寫法。",
    "除錯在扣薪列設中斷點，F5 執行、F10 逐步、F11 進入 CalcFee，區域變數視窗看 hours 是否已 Trim 後 Parse。",
    "條件中斷點 hours > 12 才停，用來抓加班公式，不要對每筆 CSV 都手動按繼續。",
    "輸出視窗看例外呼叫堆疊，InnerException 常在 FileLoadException 裡，只看外層訊息會改錯檔。",
    "Rebuild 方案後才複製資料夾交卷，Debug 目錄舊 DLL 與原始碼不一致會出現「改了沒生效」。",
    "bin\\Debug 不要當原始碼交，術科要交 .sln、.csproj、Form1.cs、Form1.Designer.cs，缺 Designer 則控制項全沒有。",
    "Form1.Designer.cs 內 InitializeComponent 不可手改到刪除事件訂閱 this.btnCalc.Click += ...。",
    "部分類別 Form1 在 Form1.cs 與 Designer 各半，重複宣告 Button btnCalc 會編譯衝突。",
    "using System.IO 與 using System.Text 才能寫 StreamReader 與 Encoding，漏 using 錯誤在名稱不存在。",
    "專案目標框架跟題目（多為 .NET Framework 4.7.2），改成 .NET 6 的 SDK 專案會讓評分機開不起來。",
    "薪資題：時薪 * 時數，加班 if (hours > 8) extra = (hours - 8) * rate * 1.33m 或 4/3m，費率以題目為準。",
    "加班 1.34 與 4.0m/3.0m 結果不同，題目寫 1.34 就用 1.34m，寫三分之四就用 4m / 3m 再 Round。",
    "勞健保若規定「未滿萬元免扣」，用 if (gross < 10000m) deduct = 0; else deduct = gross * 0.02m。",
    "成績題平均 (s1 + s2 + s3) / 3.0m，除數寫 3 會變整數除法再隱含轉 decimal，小數被截斷。",
    "及格門檻 score >= 60 含 60，寫 > 60 會讓剛好 60 顯示不及格，樣張通常含等於。",
    "三科皆及格才「通過」：if (a >= 60 && b >= 60 && c >= 60)，用平均 >= 60 會讓 100、100、20 誤判通過。",
    "發票未稅 * 0.05m 得稅額再 Round 到整數元，含稅 / 1.05m 回推未稅，方向搞反會全錯。",
    "字軌加號碼總長 10：Substring(0,2) 與 Substring(2,8)，中間空白要先 Replace 掉。",
    "停車未滿一小時當一小時計：hours = Math.Ceiling(span.TotalHours)，TimeSpan.TotalHours 是 double。",
    "跨日停車 dtpOut.Value < dtpIn.Value 要提示「離場不得早於進場」，不要讓負時數算成便宜費率。",
    "第一小時 50 元、之後每小時 30 元：if (h <= 1) fee = 50; else fee = 50 + (h - 1) * 30; h 已是進位後整數。",
    "每日上限 300 元：fee = Math.Min(fee, 300m)，跨兩日要先分段再加總，不能整段只封頂一次。",
    "會員九折在 Round 之前還是之後跟題目；先折再四捨五入與先四捨五入再折，差一分就扣輸出分。",
    "輸入驗證順序：空白、非數字、範圍（時數 0 到 24）、邏輯（離場時間），通過才寫結果 Label。",
    "錯誤時 lblResult.Text = \"\" 清掉舊金額，否則上次 1200 還留著，監評會以為這次也成功。",
    "成功路徑不要再 Show MessageBox 除非題目要求，多餘對話框會被當干擾，直接改 Label 即可。",
    "小數顯示位數與計算位數分開：內部 decimal 全精度，顯示才 Round 與 ToString(\"0.00\")。",
    "學科優先序題先乘除後加減，賦值 = 最低；布林 ! 高於 && 高於 ||，記不清就全加括號。",
    "++i 與 i++ 在單獨敘述相同，在陣列索引 arr[i++] 會先用再加，學科選錯會差一個元素。",
    "複合指定 pay += bonus 等於 pay = pay + bonus，型別要能隱含轉換，decimal += double 編譯失敗。",
    "字串 + 數字會呼叫 ToString，\"第\" + 1 + \"名\" 得「第1名」，但 \"0\" + 1 + 2 是 \"012\" 不是 3。",
    "陣列當方法參數是參考傳遞本體，方法內 arr[0] = 9 會改呼叫端；new 另一個陣列則不影響原參考。",
    "Clear 按鈕把 TextBox.Text = \"\"、ComboBox.SelectedIndex = -1、lblResult.Text = \"\"，漏清其中一個會用到舊值。",
    "測試資料至少三組：題目範例、邊界 0 與上限、非法空白與字母，只跑範例通過仍可能邊界零分。",
    "先在紙上畫輸入欄、輸出欄、公式與例外訊息表，再拖控制項，避免做完才發現少一個 DateTimePicker。",
    "公式抄題目「未滿一小時以一小時計」轉成 Ceiling，不要擅自 Floor 或直接 (int)TotalHours 截斷。",
    "輸出字串每個標點、全形冒號與空格都要比樣張，「金額:」與「金額：」差全形會被判格式錯誤。",
    "交卷檔名不可含「複本」或 (1)，資料夾層級依簡章，多包一層會讓評分程式找不到 .sln。",
    "關閉 Visual Studio 再複製，占用的 .suo 與程序鎖檔會讓 USB 複製不完整。",
    "學科題「下列何者不是 C# 關鍵字」var 是、integer 不是；string 是別名，System.String 才是型別全名。",
    "foreach 的迭代變數唯讀，item = item.Trim() 改不到 List 內容，要 for 用索引 list[i] = list[i].Trim()。",
    "ListBox 用 Items.Add 與 SelectedItem，DataGridView 用列集合，題目指定表格就不要偷懶用 ListBox。",
    "CheckedChanged 在 Form Load 設 Checked = true 就會觸發，Load 裡先解綁事件或忽略初始化階段。",
    "小數點 KeyPress 用 e.KeyChar == '.' && txt.Text.Contains(\".\") 則 e.Handled = true，避免兩個小數點。",
    "負號只允許在第一字元，e.KeyChar == '-' && txt.SelectionStart != 0 就 Handled，時數通常還要禁止負號。",
    "讀檔路徑用 dlg.FileName 完整路徑，不要寫死 C:\\\\Test\\\\a.csv，評分機沒有這個資料夾。",
    "相對路徑 AppDomain.CurrentDomain.BaseDirectory 在 Debug 下，交卷後執行目錄不同，術科開檔應用對話框。",
    "CSV 空行 if (string.IsNullOrWhiteSpace(line)) continue; 空行 Parse 會當成格式錯誤中斷。",
    "欄位「TRUE/FALSE」轉 bool 用 string.Equals(s, \"TRUE\", OrdinalIgnoreCase)，Convert.ToBoolean(\"1\") 會例外。",
    "ParseExact(s, \"yyyy/MM/dd\", CultureInfo.InvariantCulture) 避免系統地區把斜線當日期分隔而搞錯月日。",
    "CultureInfo.InvariantCulture 搭配 decimal.Parse 可避免小數點被當成千分位，中文 Windows 偶發格式陷阱。",
    "Math.Floor 無條件捨去、Ceiling 進位、Truncate 朝零；金額四捨五入不是 Floor，停車進位小時才用 Ceiling。",
    "Math.Abs 算時差前可防負值，但正確做法是先比較進出場，負值應拒絕而非取絕對值收費。",
    "隨機亂數丙級少用，若題目要抽獎 new Random() 不要放迴圈內，重複種子會得到相同序列。",
    "註解 // 說明費率來源即可，大段註解不計分；把程式碼註解掉卻交卷等於該功能沒做。",
    "學科常見：WinForms 事件驅動，沒按按鈕 Load 以外的 Click 不會跑，主流程不要寫在 Main 無限迴圈。",
    "Program.cs 的 Application.Run(new Form1()) 不可改成 Console，丙級術科是表單應用不是主控台。",
    "訊息「計算完成」若樣張沒有就不要加，多字元輸出一律格式錯誤，寧少提示不多字。",
    "核對清單：檔名、namespace、Any CPU、標題 Text、空字串、MidpointRounding、ToString 樣式、UTF-8、最後 Rebuild。",
    "時間分配先做讀寫檔與計算核心，美化 Anchor 放最後；核心跑通才有分數，版面微調通常佔分較低。",
]

H45 = [
    "Word 標題段落套「標題 1」「標題 2」樣式，目錄與多層次清單才抓得到層級；只改字級看起來像標題，功能變數仍是內文。",
    "多層次清單連結到標題樣式後，在清單庫選該清單，手動打「1.1.1」下一章不會自動重編。",
    "定義新的多層次清單時，層級 1 對應標題 1、層級 2 對應標題 2，對錯層會造成目錄縮排全亂。",
    "編號格式含「第」與「章」要寫在清單定義的編號格式框，不要在段落前後自己鍵入，否則重編時變雙重編號。",
    "分節符號選「下一頁」才能讓新節從新頁開始並擁有獨立頁首；「連續」分節頁首分開但還黏在同一頁。",
    "「分頁符號」只換頁不開新節，奇偶頁頁首、欄數、紙張方向仍跟著上一節，看起來換頁了設定卻沒斷。",
    "插入分節後先取消「連結到前一節」，再改偶數頁頁首，否則甲節頁首會覆寫乙節。",
    "頁首與頁尾工具勾「奇偶頁不同」，偶數頁才出現獨立編輯區；只改奇數頁，背面仍是舊內容。",
    "「第一頁不同」給封面無頁碼，封面後第一個內文節才開始編碼，未分節會連封面一起編頁。",
    "頁碼選「第 x 頁，共 y 頁」會插入 PAGE 與 NUMPAGES 功能變數，手動打「第 3 頁，共 12 頁」頁數一增就錯。",
    "起始頁碼在頁碼格式對話框設「起始編號 1」，新節若「續前節」會接 17，封面後內文常被要求從 1。",
    "目錄用參考資料→目錄→自訂目錄，顯示層級勾到標題 3；用鍵盤打一串標題加定位點，更新功能變數不會刷新。",
    "更新目錄選「更新整個目錄」才會改標題文字與頁碼，「只更新頁碼」改過標題的條目仍是舊字。",
    "目錄功能變數 TOC 的開關 \\o \"1-3\" 控制層級，改樣式層級後若沒更新 TOC，列印稿仍少一層。",
    "註腳插入在句號前，編號採每節重編或連續依題目；尾註在文件或節末，把註腳當尾註插入會跑錯位置。",
    "註腳分隔線隨節，分節後可能出現多餘短線，要在草稿檢視點分隔線段落去格式，不能只刪註腳本文。",
    "交叉參照選「標題」或「書籤」並勾「插入為超連結」，標題改字後更新功能變數，硬打「見第 3 頁」會過期。",
    "書籤名稱勿含空白，交叉參照才列得出；選取範圍含段落標記會讓書籤吃到下一段標題。",
    "圖說用參考資料→插入圖說，標籤「圖」自動編號；手動「圖 1-1」後面圖片刪除後編號不會補洞。",
    "圖表編號與圖說分開的交叉參照要選「只有標籤和編號」，選「整項圖說」會把說明文字也灌進正文。",
    "郵件合併先選文件類型「信件」，資料來源用現有清單指向試題 Excel，工作表名稱與欄名必須與合併功能變數一致。",
    "插入合併功能變數用「插入合併欄位」，不要複製 Excel 某一列當範本，完成合併時仍是死文字。",
    "規則→如果…那麼…否則… 依欄位「繳費狀態」輸出「已繳」或「催繳」，用 Word 裡手改單筆，下一次合併會被蓋掉。",
    "完成合併選「編輯個別文件」才產生可交的結果檔；只預覽仍連著資料來源，評分機沒有該 xlsx 會全空白。",
    "合併前「編輯收件人清單」取消空白列與標題誤判列，否則第一封信變成欄名「姓名」「地址」。",
    "合併用工作表第一列必須是欄名且無合併儲存格，合併儲存格會讓 Word 讀到空欄位。",
    "Word 表格公式 =SUM(ABOVE) 放在欄底，插入或刪列後要 F9 更新；Excel 式 SUM 貼進來是純文字不會算。",
    "表格公式儲存格對齊與數字格式在公式對話框設 0.00，只改字型大小不會改計算結果的小數位。",
    "浮水印用設計→浮水印→自訂文字，文字、字型、淡化勾選依題目；在頁首手動打斜字，分節後有的頁沒有。",
    "圖片浮水印設在頁首的浮於文字上並置中，縮放依樣張；當內文插入圖片當背景，內文一刪圖就消失。",
    "限制編輯勾「不允許任何變更（唯讀）」再「是，啟動強制保護」，密碼依試題；只按限制而不啟動，檔案仍可改。",
    "啟動保護前先把允許填寫的內容控制項或節例外設好，整份唯讀後監評無法輸入姓名會倒扣。",
    "追蹤修訂開啟後，刪除顯示為刪除線、插入為底線，接受或拒絕才真正改文件；隱藏標記列印會看起來「沒修過」。",
    "顯示標記選「所有標記」，最終狀態檢視不是修訂紀錄，評分若查修訂窗格會認定未使用追蹤。",
    "區段（節）紙張直向改橫向只改該節，未分節會整份變橫，封面直、附表橫必須在表前插入「下一頁」分節。",
    "欄位分欄是版面設定的欄，不是按 Tab 假分欄；分節後才能一節單欄一節雙欄。",
    "尋找取代勾「使用萬用字元」，^p 是段落標記，[0-9]{3} 找三連數字；未勾萬用字元時 {3} 被當普通字元。",
    "取代^t 為一個空格可清多餘定位點，連續空白用「空白{2,}」類模式，手動逐段刪會漏頁。",
    "特殊格式尋找「樣式：標題 1」可一次改該層級，選取整篇後改字型會把本文也改掉。",
    "章節起始若要求「奇數頁」，版面設定→版面配置→區段起始選奇數頁，Word 會自動插入空白偶數頁，不是手打空白頁。",
    "空白頁刪不掉往往是分節符號佔了一頁，顯示編輯標記後刪分節符號，不要連刪前一段正文。",
    "行距「固定行高 24 點」與「倍數 1.5」不同，固定行高切到大圖會裁字，題目寫固定就不要用倍數。",
    "段落前後距在樣式裡改，不要每段手動，樣式未更新時後面貼上的文字又變回 0 點。",
    "框線若只要標題下底線，用段落框線而非字元底線，換行時字元底線會斷。",
    "頁面邊界上下左右公分數對試題，裝訂邊在左；邊界看起來相近但差 0.2 公分，版面設定仍算錯。",
    "文件格線與文字對齊若題目要求，版面配置→文件格線，未開時行距對了仍可能被判未對齊格線。",
    "智慧型引號與直引號，尋找取代時先貼試題指定的符號，系統自動取代成彎引號會與樣張不符。",
    "中英交錯時不要用空格硬擠，用樣式的標點擠壓；硬空格在兩端對齊時會出現大洞。",
    "目錄頁本身通常不要出現在目錄裡，封面節不要套標題 1，否則 TOC 第一條變成「封面」。",
    "更新功能變數全選 Ctrl+A 再 F9，含交叉參照、目錄、表公式；只更新目錄會漏掉圖說編號。",
    "列印預覽看奇偶頁頁首是否對調正確，單頁模式看不出偶數頁，要雙頁顯示。",
    "Word 交件副檔名 .docx，相容模式 .doc 會丟內容控制項與部分目錄開關。",
    "Excel 名稱管理員定義稅率 TaxRate 指向單一儲存格，公式寫 =金額*TaxRate，改稅率不用滿表尋找 0.05。",
    "名稱範圍不要含整欄空白到 1048576 列，SUMIFS 會變慢且資料驗證清單出現大量空值。",
    "資料驗證「清單」來源用逗號分隔或 =等級表，錯誤警示選停止，才能擋清單外輸入；只設警告考生仍可硬打。",
    "驗證「整數」介於 0 與 100 給成績欄，小數 80.5 應被拒；設成小數又允許負數會與試題不符。",
    "圈釋無效資料可一次看到驗證被略過的儲存格，交卷前用它抓從別處貼上、沒觸發下拉的值。",
    "IF 巢狀超過三層改 IFS(條件1,值1,條件2,值2,TRUE,其他)，2016 有 IFS；2013 舊檔沒有會顯示名稱錯誤。",
    "IF 的邏輯測出空白用 =IF(A2=\"\",\"\",公式)，空白當 0 會讓平均分數被拉低。",
    "SUMIFS 加總金額，條件範圍與加總範圍列數必須同長，一邊整欄一邊 A2:A100 會 #VALUE!。",
    "COUNTIFS 多條件是 AND，要 OR 就兩段 COUNTIFS 相加再扣重疊，硬塞進一個 COUNTIFS 會少算。",
    "AVERAGEIF 會忽略條件外，平均「已出貨」不要先篩選再對可見列平均，篩選一關結果就變。",
    "VLOOKUP 第四參數 FALSE 或 0 做精確比對，TRUE 要求第一欄遞增否則可能取錯鄰近列。",
    "鍵值在右欄時改用 INDEX(傳回範圍,MATCH(鍵,查找欄,0))，VLOOKUP 無法向左取欄。",
    "MATCH 第三參數 0 精確，1 或 -1 是近似且需排序；成績等第表未排序用 1 會取到錯的級距。",
    "INDEX 列號由 MATCH 提供，兩個 MATCH 可做二維表：列對品名、欄對月份。",
    "HLOOKUP 查第一列標題，月份當列標題時用它，仍記得第四參數精確比對。",
    "IFERROR(VLOOKUP(...),\"無此編號\") 把 #N/A 換成指定文字，題目若要保留錯誤值就不要包 IFERROR。",
    "ROUND(值,0) 到整數、ROUND(值,2) 到分；銀行家捨入不是 Excel ROUND，Excel ROUND 是 5 進位遠離 0。",
    "INT 無條件捨去到整數（負數朝負無窮），TRUNC 朝零；抽成到元用 INT 還是 ROUND 跟試題用詞。",
    "日期在 Excel 是序列，1 是 1900/1/1，兩日期相減得天數；顯示 yyyy/mm/dd 只是格式，真正值仍是數字。",
    "TODAY() 每天變，試題要固定結帳日就輸入該日期或指到參數格，交卷隔天分數會變的不要用 TODAY。",
    "EOMONTH、DATE(年,月+1,0) 取月末，文字「2026/8/18」要用 DATEVALUE 或 VALUE 才能加天數。",
    "自訂格式 0.00 強制兩位小數，0.00% 把 0.05 顯示 5.00%，已乘過 100 的數再套 % 會變成 500%。",
    "格式 [藍色]0.00;[紅色]-0.00;\"-\" 讓零顯示橫線，這是顯示不是值，SUM 仍含 0。",
    "文字格式的數字不能直接 SUM，VALUE 或乘 1 轉回，左上角綠三角常代表以文字儲存的數字。",
    "條件格式用公式 =$D2<60 套用到 D2:D100，絕對欄、相對列，整欄選 $D$2 會每列都去比第二列。",
    "圖示集與色階看的是儲存格值，隱藏列仍參與規則；只想對可見資料上色要先確認規則範圍。",
    "刪除條件格式用「清除規則」，把填色當條件格式，一改數字顏色不會跟著變，評分查規則會沒有。",
    "樞紐分析表來源含標題列、無空白標題、無合併儲存格，在資料中插入列後要變更資料來源。",
    "值欄位摘要用加總不是計數，文字混進金額欄會被迫計數，看起來筆數對、金額卻少兩零。",
    "樞紐版面列標籤顯示成大綱或表格式依題目，壓縮形式會把多層欄位疊在同一欄，列印對不齊。",
    "取消「列總計」若樣張沒有總計，多餘總計列會被當多餘資料。",
    "切片器插入後連到正確樞紐，一個切片器可連多張表，沒連到的表篩選了畫面也不動。",
    "報表篩選與切片器同時存在時，交卷前看篩選器是否「全部」，題目若要看全資料，殘留篩選會少列。",
    "圖表次座標軸給單位不同的數列，例如金額與人數，兩條都在主軸會讓人數貼近零。",
    "組合圖直條加折線，資料數列格式→繪製在次座標軸；只改線條顏色沒設次軸仍共用刻度。",
    "圖表標題連到儲存格 =工作表!B1，改標題文字題目一改來源標題會自動變；圖上硬打死字不會連動。",
    "資料標籤百分比來自「值」相對該數列，圓形圖才有百分比標籤，直條圖勿硬加 % 造成誤解。",
    "保護工作表勾「保護工作表」，允許「選取已解除鎖定儲存格」，輸入格取消鎖定、公式格鎖定。",
    "未解除輸入格鎖定就保護，考生連題目要求填的格子都點不到；全不鎖定又保護等於沒保護。",
    "保護密碼依試題，空白密碼也是一種設定，評分若嘗試編輯公式應被拒。",
    "分頁列印設列印標題「顶端标题行」$1:$1，每頁重複表頭；只在第一頁手動複製表頭，第二頁沒有。",
    "列印標題是「頁面配置」列印標題，不是在每一個分頁手動插入列；分頁符預覽可調水平垂直分頁。",
    "縮放列印「將工作表調整為 1 頁寬」避免右邊一欄落到第 2 頁，高度是否 1 頁看題目會不會把字縮太小。",
    "頁首頁尾用 &[頁] / &[總頁數] 功能，手動打頁碼在列印標題列，頁數一變就錯。",
    "列印範圍設到資料最後一列，下面殘留測試數字會多印一頁。",
    "凍結窗格凍在標題下一列，與「分割」不同；交卷不一定查凍結，但操作錯把分割線留下會被看到。",
    "排序前插入空白列當區隔會讓排序只排一半，先移除空白列，鍵值欄不可混用數字與文字。",
    "進階篩選可複製到其他位置，自動篩選只是隱藏列，交卷若要求「篩選結果在新範圍」，用進階篩選。",
    "SUBTOTAL(9,範圍) 只加總可見列，SUM 會連隱藏列；篩選後總計要用 SUBTOTAL 才跟畫面一致。",
    "陣列公式在 2019 動態陣列可直接輸入，2016 可能要 Ctrl+Shift+Enter；試題版本不一致時用輔助欄較穩。",
    "SUMPRODUCT((條件範圍=條件)*(金額)) 可當陣列加總，條件範圍勿含文字標題否則乘起來 #VALUE!。",
    "TEXT(日期,\"yyyy年m月\") 轉文字後不能再拿去比日期大小，分組月份應保留真正日期或用 EOMONTH。",
    "LEFT/MID/RIGHT 拆編號，LEN 先確認位數；全形數字與半形不同，VALUE 轉失敗先 SUBSTITUTE。",
    "TRIM 去前後與多餘中間空白，CLEAN 去非列印字元，CSV 匯入後 VLOOKUP 對不上多半是隱形空白。",
    "查找與取代「格式」可改儲存格顏色，但公式裡的值不會因填色改變，條件邏輯仍要寫在公式或條件格式。",
    "跨工作表引用 銷貨!D2 工作表名有空白要加單引號 '1 月銷貨'!D2，漏引號會 #REF! 或名稱錯誤。",
    "複製工作表時公式若用相對參照會跑掉，稅率應絕對 $B$1 或名稱，跨表複製才不變。",
    "循環參照狀態列會顯示，稅額格子又去加總含自己的範圍，結果飄動或零，交卷前看狀態列。",
    "Power Query 從表格或範圍取得資料，第一列當標題，轉換型別再關閉並載入；只貼上值，來源一改不會刷新。",
    "查詢步驟若「變更型別」把代號欄變成整數，前導零訂單編號會消失，該欄應維持文字。",
    "合併查詢對應 SQL 的 JOIN，鍵值型別兩邊都要文字或都要數字，一邊文字一邊數字對不上。",
    "乙級若沒要求 Power Query，用公式與樞紐即可，多餘查詢連到外部路徑評分機打不開。",
    "時間分配：先 Word 樣式、分節、頁碼、目錄，再 Excel 名稱、驗證、公式、樞紐、圖表，最後兩邊列印預覽。",
    "Word 核對：樣式層級、分節位置、取消連結到前一節、PAGE/NUMPAGES、目錄功能變數、交叉參照已 F9。",
    "交卷核對 VLOOKUP 第四參數、SUMIFS 範圍同長、樞紐加總而非計數、列印標題、保護鎖定例外、自訂格式。",
    "看起來正確但設定錯的典型：目錄是手打、頁碼是死文字、平均是看篩選後心算填入、圖表次軸沒開。",
    "另存工作檔再動刀，試題原始 xlsx/docx 保留；覆寫原始檔做錯一步可能無法還原郵件合併資料來源。",
    "檔名與儲存位置依簡章，Word 與 Excel 分開交，不要把 xlsx 嵌進 docx 當唯一附件除非題目要求。",
    "字型新細明體與標楷體依題目，從別台電腦複製來的主題字型評分機沒有會變。",
    "單位換算公分與英吋，邊界對話框確認單位，1 英吋當 1 公分會整頁版心錯位。",
    "試題「不得使用手動分頁來模擬章節」就要分節；「看起來已換頁」不夠，要在顯示編輯標記下見到分節符號。",
    "試題寫不得以常數取代公式時，結果格必須留公式，貼上值後畫面數字對、一改輸入就不會動。",
    "條件格式與篩選不要互相當對方用：篩選隱藏列不算上色條件已滿足，題目要紅色標記不及格仍應設規則。",
    "樞紐重新整理後切片器可能清空選取，交卷前再點一次題目指定的年度。",
    "圖表來源勿含空白列與合計列，合計再進圖會讓直條高一截，雙計總計。",
    "次座標軸刻度最大值手動設過，資料一更新可能裁切，交卷前改回自動除非題目指定刻度。",
    "Word 表格不可把整張轉成文字再排版，題目要表格公式與框線，轉文字後公式消失。",
    "儲存格合併只給標題列，資料區合併會害排序、樞紐、資料驗證清單錯位。",
    "隱藏欄給輔助計算可以，交卷若要求顯示計算過程就得取消隱藏，評分展開後要看得到公式。",
    "群組與大綱的加號不要留在列印範圍，列印會多出階層符號。",
    "註解與執行備註乙級通常不計分，試題沒要就刪掉，避免遮住儲存格被當成多餘物件。",
    "最終十分鐘：Word 列印預覽奇偶頁、Excel 分頁預覽、關閉追蹤修訂顯示後再看一次「最終狀態」是否仍要留標記。",
    "郵件合併結果檔與主文件都要依簡章繳交時，缺主文件會被認定未用合併功能。",
    "下拉驗證在保護後仍可選，前提是該格未鎖定；鎖定又保護則清單也點不了。",
    "目錄頁碼與內文頁首不一致，多半是目錄未更新或分節起始編號設錯，不要改目錄文字去遷就。",
    "交叉參照顯示「錯誤！找不到參照來源」代表書籤被刪，重新插入參照，不要把錯誤文字當正文留下。",
    "浮水印淡化不足在列印預覽會擋正文，題目若要求「不影響閱讀」檢查淡化與字型大小。",
    "限制編輯與追蹤修訂可並存，但啟動保護後無法再接受修訂，順序應先處理修訂再保護。",
    "萬用字元取代前先在複本試三筆，錯誤模式 ^? 當單字元，可能把不該刪的標點吃掉。",
    "ROUND 寫進公式與儲存格顯示位數不同：顯示 0 位內部仍可能是 1.2，再乘會露出尾差，關鍵金額要在公式裡 ROUND。",
    "INT(金額*100+0.5)/100 是舊式四捨五入，與 ROUND(金額,2) 在負數時可能不同，以 ROUND 為準除非試題指定 INT。",
    "INDEX+MATCH 的 MATCH 範圍必須單列或單欄，誤選區塊會 #N/A 或 #VALUE!。",
    "VLOOKUP 查找值型別與第一欄型別不一致，例如數字 1001 對文字 \"1001\"，先兩欄都 TEXT 或都 VALUE。",
    "COUNTBLANK 把公式回傳 \"\" 算空白，COUNT 不算文字，成績人數用 COUNTA 還是 COUNT 要看是否含文字等第。",
    "樞紐「值顯示方式」選佔總計百分比，與手動寫金額/總計不同，總計一篩選百分比會重算。",
    "切片器樣式與報表主題顏色依題目，可讀性通常不細扣，但切片器蓋住儲存格會被當版面錯誤。",
    "頁尾置中放 PAGE、頁首放節名稱時兩邊都要取消連結到前一節，只改一處另一處仍連動。",
    "本節頁數用 SECTIONPAGES，NUMPAGES 是整份頁數；封面加目錄後若樣張要整份總頁，勿誤用本節頁數。",
]


def numbered(items):
    assert len(items) == 150, len(items)
    out = []
    bodies = []
    for i, t in enumerate(items, 1):
        assert t and t[-1] not in "：:", t
        for b in BANNED:
            assert b not in t, (b, t[:40])
        assert not CHAP_RE.search(t), t[:40]
        assert not STEP_RE.search(t), t[:40]
        bodies.append(t)
        out.append(f"{i:03d}、{t}")
    assert len(set(bodies)) == 150
    prefixes = [t[:6] for t in bodies]
    # allow some overlap but flag heavy template
    from collections import Counter
    c = Counter(prefixes)
    heavy = [k for k, v in c.items() if v >= 4]
    assert not heavy, heavy
    return out


def patch(path: Path, items):
    data = json.loads(path.read_text(encoding="utf-8"))
    data["chatgptHighlights"] = numbered(items)
    data["chatgptStatus"] = "complete"
    data["highlightsSource"] = "grok"
    data["highlightsCapturedAt"] = STAMP
    data["updatedAt"] = "2026-08-18"
    text = json.dumps(data, ensure_ascii=False, indent=2) + "\n"
    path.write_text(text, encoding="utf-8")
    hl = data["chatgptHighlights"]
    assert len(hl) == 150
    assert hl[0].startswith("001、")
    assert hl[-1].startswith("150、")
    return path


def main():
    p44 = patch(ROOT / "06_computer_info-20260716-44.json", H44)
    p45 = patch(ROOT / "06_computer_info-20260716-45.json", H45)
    print("OK", p44)
    print("OK", p45)
    print("n44", len(H44), "n45", len(H45))
    s44, s45 = set(H44), set(H45)
    print("overlap", len(s44 & s45))


if __name__ == "__main__":
    main()
